#!/usr/bin/env python3
"""Build the reviewed Alpha POS Postman collection from genpostman inventories.

The source inventories are intentionally generated by Django's URL resolver so
the collection can be refreshed after routes change without hand-maintaining a
second route list:

    cd alpha_pos_server
    python manage.py genpostman --base-url '{{cloudBaseUrl}}' \
        --output /tmp/alpha_server_raw_postman.json

    cd alpha_pos_local
    python manage.py genpostman --base-url '{{localBaseUrl}}' \
        --output /tmp/alpha_local_raw_postman.json

Then run this file. It emits one representative request per distinct registered
HTTP path. When a Django view accepts several methods, every accepted method is
listed in the request description. Django's generated /admin/ UI is deliberately
outside this API collection.
"""

from __future__ import annotations

import argparse
import json
import re
import uuid
from collections import OrderedDict
from pathlib import Path
from typing import Any, Iterable


SCHEMA = "https://schema.getpostman.com/json/collection/v2.1.0/collection.json"
DEFAULT_SERVER_RAW = Path("/tmp/alpha_server_raw_postman.json")
DEFAULT_LOCAL_RAW = Path("/tmp/alpha_local_raw_postman.json")
DEFAULT_OUTPUT = Path(__file__).with_name("Alpha_POS_API.postman_collection.json")

METHOD_PRIORITY = ("GET", "POST", "PATCH", "PUT", "DELETE")
MUTATION_METHODS = {"POST", "PATCH", "PUT"}

BASE_VARIABLES = OrderedDict(
    [
        ("cloudBaseUrl", "https://pos.example.invalid"),
        ("localBaseUrl", "http://127.0.0.1:8000"),
        ("cloudWsBaseUrl", "wss://pos.example.invalid"),
        ("localWsBaseUrl", "ws://127.0.0.1:8000"),
        ("adminToken", ""),
        ("posToken", ""),
        ("waiterToken", ""),
        ("sessionToken", ""),
        ("courierToken", ""),
        ("courierRefreshToken", ""),
        ("customerToken", ""),
        ("branchToken", ""),
        ("cloudSyncToken", ""),
        ("managementToken", ""),
        ("telegramWebhookSecret", ""),
        ("paymentWebhookSecret", ""),
        ("branchId", "00000000-0000-4000-8000-000000000001"),
        ("shiftUuid", "00000000-0000-4000-8000-000000000003"),
        ("manifestDigest", "0000000000000000000000000000000000000000000000000000000000000000"),
        ("deviceId", "postman-dev-device"),
        ("idempotencyKey", "postman-example-idempotency-key"),
        ("planId", "1"),
        ("receiptId", "1"),
        ("notificationId", "1"),
        ("redemptionId", "1"),
        ("orderDiscountId", "1"),
        ("destinationLocationId", "2"),
        ("destinationUnitId", "2"),
        ("adminEmail", "admin@example.invalid"),
        ("adminPassword", "change-me"),
        ("posEmail", "cashier@example.invalid"),
        ("posPassword", "change-me"),
        ("waiterEmail", "waiter@example.invalid"),
        ("waiterPassword", "change-me"),
        ("courierPhone", "+998900000000"),
        ("courierPassword", "change-me"),
        ("customerPhone", "+998900000001"),
        ("telegramInitData", ""),
        ("fromDate", "2026-01-01"),
        ("fromAt", "2026-01-01T07:00:00+05:00"),
        ("toAt", "2026-01-02T03:00:00+05:00"),
        ("page", "1"),
        ("perPage", "50"),
        ("search", ""),
        ("latitude", "41.3111"),
        ("longitude", "69.2797"),
        ("addressQuery", "Tashkent"),
        ("phone", "+998900000001"),
        ("amount", "100000.00"),
        ("currency", "UZS"),
    ]
)

ID_DEFAULTS = {
    "slug": "sample-slug",
    "name": "cashier",
    "barcode": "100000000001",
    "action": "submit",
    "kind": "contract",
    "phone": "+998900000001",
    "typeSlug": "shift_closed",
    "claimToken": "00000000-0000-4000-8000-000000000002",
    "qrToken": "replace-with-minted-qr-token",
}

WEBSOCKETS = {
    "cloud": [
        ("Order Queue", "{{cloudWsBaseUrl}}/ws/orders/?token={{adminToken}}"),
        ("Kitchen Display", "{{cloudWsBaseUrl}}/ws/kds/?token={{adminToken}}"),
        ("Cashier Control", "{{cloudWsBaseUrl}}/ws/cashiers/?token={{adminToken}}"),
        ("Courier Client", "{{cloudWsBaseUrl}}/ws/courier/?token={{courierToken}}"),
        ("Cashier Courier Feed", "{{cloudWsBaseUrl}}/ws/cashier/?token={{adminToken}}"),
        (
            "SmartFood Order Tracking",
            "{{cloudWsBaseUrl}}/ws/smartfood/orders/{{orderId}}/?token={{customerToken}}",
        ),
    ],
    "local": [
        ("Order Queue", "{{localWsBaseUrl}}/ws/orders/?token={{posToken}}"),
        ("Kitchen Display", "{{localWsBaseUrl}}/ws/kds/?token={{posToken}}"),
        ("Cashier Control", "{{localWsBaseUrl}}/ws/cashiers/?token={{posToken}}"),
        ("Courier Client", "{{localWsBaseUrl}}/ws/courier/?token={{courierToken}}"),
        ("Cashier Courier Feed", "{{localWsBaseUrl}}/ws/cashier/?token={{posToken}}"),
    ],
}


def flatten(items: Iterable[dict[str, Any]]) -> list[dict[str, Any]]:
    """Return every Postman request item below an arbitrary folder tree."""
    result: list[dict[str, Any]] = []
    for item in items:
        if "request" in item:
            result.append(item)
        result.extend(flatten(item.get("item", [])))
    return result


def raw_url(item: dict[str, Any]) -> str:
    value = item["request"]["url"]
    return value["raw"] if isinstance(value, dict) else value


def source_path(url: str) -> str:
    return url.replace("{{base_url}}", "").split("?", 1)[0]


def source_groups(
    edition: str, source: dict[str, Any]
) -> OrderedDict[str, list[dict[str, Any]]]:
    """Group generated requests while restoring two slash-sensitive aliases.

    Django's resolver distinguishes these registered paths, but the shared raw
    generator normalizes away their trailing slash. Preserve the actual URLconf
    contract here so the final collection remains path-complete.
    """
    grouped: OrderedDict[str, list[dict[str, Any]]] = OrderedDict()
    for item in flatten(source["item"]):
        grouped.setdefault(source_path(raw_url(item)), []).append(item)

    if edition == "cloud":
        alias = "/api/admins/analytics/comparison"
        candidates = grouped.get(alias, [])
        if len(candidates) == 2 and all(
            item["request"]["method"] == "GET" for item in candidates
        ):
            grouped[alias] = [candidates[0]]
            grouped[alias + "/"] = [candidates[1]]
    else:
        alias = "/orders/:order_id/status"
        candidates = grouped.get(alias, [])
        by_method = {item["request"]["method"]: item for item in candidates}
        if {"PATCH", "POST"}.issubset(by_method):
            grouped[alias] = [by_method["PATCH"]]
            grouped[alias + "/"] = [by_method["POST"]]

    exact: OrderedDict[str, list[dict[str, Any]]] = OrderedDict()
    for path, items in grouped.items():
        restored = restore_trailing_slash(edition, path)
        if restored in exact:
            raise ValueError(
                f"slash restoration collided for {edition}: {path} -> {restored}"
            )
        exact[restored] = items
    return exact


def restore_trailing_slash(edition: str, path: str) -> str:
    """Restore exact slash style that the raw generator intentionally trims."""
    if path.endswith("/"):
        return path
    if edition == "cloud":
        if path.startswith(
            (
                "/api/admins/stock/",
                "/api/admins/hr/",
                "/api/admins/discounts/",
                "/api/admins/notifications/",
                "/api/admins/cashbox/",
                "/auth/courier/",
                "/courier/",
                "/orders/",
                "/payments/",
            )
        ):
            return path + "/"
        if path in {"/api/customer-bot/webhook", "/api/admins/couriers"}:
            return path + "/"
        return path
    if path.startswith(
        (
            "/api/cashbox/",
            "/api/qr/",
            "/auth/courier/",
            "/courier/",
            "/payments/",
        )
    ):
        return path + "/"
    if path == "/api/couriers":
        return path + "/"
    if re.fullmatch(r"/orders/:[^/]+/(accept|decline)", path):
        return path + "/"
    return path


def camel(value: str) -> str:
    parts = value.split("_")
    return parts[0] + "".join(part[:1].upper() + part[1:] for part in parts[1:])


def path_variable_name(raw_name: str, path: str) -> str:
    if raw_name == "token":
        return "qrToken"
    if raw_name == "claim_token":
        return "claimToken"
    if raw_name == "name":
        return "roleName"
    if raw_name == "kind":
        return "documentKind"
    if raw_name == "phone":
        return "phone"
    return camel(raw_name)


def postman_path(path: str) -> tuple[str, set[str]]:
    """Translate Django generator :vars into collection-scoped {{vars}}."""
    variables: set[str] = set()

    def replace(match: re.Match[str]) -> str:
        name = path_variable_name(match.group(1), path)
        variables.add(name)
        return "{{" + name + "}}"

    return re.sub(r":([A-Za-z_][A-Za-z0-9_]*)", replace, path), variables


def title_case_name(name: str) -> str:
    name = re.sub(r"\bList (?=(?:.* Detail|Me$|Settings$|Config$))", "", name)
    return name.replace("One C", "1C").replace("Ai ", "AI ")


def segment(path: str, prefix: str) -> str:
    rest = path[len(prefix) :].lstrip("/")
    return rest.split("/", 1)[0] or "Overview"


def cloud_folders(path: str) -> list[str]:
    root = ["Cloud Server"]
    if path == "/healthz" or path.startswith("/api/licensing/"):
        return root + ["Health & Licensing"]
    if path.startswith("/api/sync/"):
        return root + ["Branch Synchronization"]
    if path.startswith("/api/fiscalization/"):
        return root + ["Fiscalization"]
    if path.startswith("/api/customer-bot/"):
        return root + ["Telegram Customer Bot"]
    if path.startswith("/api/smartfood/"):
        group = segment(path, "/api/smartfood/")
        labels = {
            "auth": "Authentication",
            "me": "Profile",
            "config": "Configuration",
            "catalog": "Catalog",
            "cart": "Cart & Quotes",
            "orders": "Orders",
            "addresses": "Addresses",
            "geo": "Geocoding",
            "loyalty": "Loyalty & Rewards",
            "rewards": "Loyalty & Rewards",
            "redemptions": "Loyalty & Rewards",
            "support": "Support",
        }
        return root + ["SmartFood Customer", labels.get(group, "Other")]
    if path.startswith("/api/admins/stock/"):
        group = segment(path, "/api/admins/stock/")
        labels = {
            "settings": "Configuration & Alerts",
            "alerts": "Configuration & Alerts",
            "locations": "Master Data",
            "units": "Master Data",
            "categories": "Master Data",
            "items": "Items & Levels",
            "levels": "Items & Levels",
            "low-stock": "Items & Levels",
            "adjust": "Transactions & Reservations",
            "reserve": "Transactions & Reservations",
            "release-reservation": "Transactions & Reservations",
            "transactions": "Transactions & Reservations",
            "batches": "Batches",
            "suppliers": "Suppliers",
            "purchase-orders": "Purchasing & Receiving",
            "purchase-order": "Purchasing & Receiving",
            "purchase-order-items": "Purchasing & Receiving",
            "receiving": "Purchasing & Receiving",
            "recipes": "Recipes & Production",
            "recipe-ingredients": "Recipes & Production",
            "production-orders": "Recipes & Production",
            "transfers": "Transfers & Counts",
            "counts": "Transfers & Counts",
            "variance-codes": "Transfers & Counts",
            "product-links": "POS Product Links",
            "products": "POS Product Links",
            "orders": "POS Stock Integration",
            "ai": "AI Assistant",
        }
        return root + ["Cloud Administration", "Inventory & Stock", labels.get(group, "Other")]
    if path.startswith("/api/admins/hr/"):
        group = segment(path, "/api/admins/hr/")
        labels = {
            "departments": "People",
            "employees": "People",
            "expense-categories": "Expenses",
            "expenses": "Expenses",
            "salaries": "Payroll",
            "cash": "HR Cash Ledger",
            "contracts": "Contracts",
            "leave-types": "Leave",
            "leaves": "Leave",
            "leave-balances": "Leave",
            "attendance": "Attendance",
            "documents": "Documents",
            "reviews": "Performance",
            "goals": "Performance",
            "events": "Timeline",
        }
        return root + ["Cloud Administration", "Human Resources", labels.get(group, "Other")]
    if path.startswith("/api/admins/discounts/"):
        return root + ["Cloud Administration", "Discounts"]
    if path.startswith("/api/admins/notifications/"):
        group = segment(path, "/api/admins/notifications/")
        labels = {
            "settings": "Delivery Settings",
            "types": "Notification Types",
            "templates": "Templates",
            "queue": "Queue",
            "logs": "Delivery Logs",
            "loyalty": "Loyalty",
            "qr": "QR Tokens",
        }
        return root + ["Cloud Administration", "Notifications & Loyalty", labels.get(group, "Other")]
    if path.startswith("/api/admins/cashbox/"):
        return root + ["Cloud Administration", "Cashbox"]
    if path.startswith("/api/admins/smartfood/"):
        group = segment(path, "/api/admins/smartfood/")
        labels = {
            "config": "Configuration",
            "orders": "Order Dispatch",
            "cashiers": "Connectivity",
            "pos": "Connectivity",
            "catalog": "Catalog Review",
            "products": "Catalog Review",
            "categories": "Catalog Review",
            "sizes": "Catalog Options",
            "topping-groups": "Catalog Options",
            "toppings": "Catalog Options",
            "loyalty": "Loyalty",
        }
        return root + ["Cloud Administration", "SmartFood Management", labels.get(group, "Other")]
    if path.startswith("/api/admins/couriers"):
        return root + ["Cloud Administration", "Courier Management"]
    if path.startswith("/api/admins/"):
        group = segment(path, "/api/admins/")
        labels = {
            "permissions": "Authentication & Access",
            "roles": "Authentication & Access",
            "auth-login": "Authentication & Access",
            "auth-logout": "Authentication & Access",
            "auth-logout-all": "Authentication & Access",
            "auth-me": "Authentication & Access",
            "auth-change-password": "Authentication & Access",
            "auth-sessions": "Authentication & Access",
            "categories": "Menu Catalog",
            "products": "Menu Catalog",
            "orders": "Orders",
            "places": "Places & Tables",
            "tables": "Places & Tables",
            "users": "Users & Customers",
            "customers": "Users & Customers",
            "inkassa": "Treasury & Inkassa",
            "treasury": "Treasury & Inkassa",
            "app-settings": "Application Settings",
            "shift-templates": "Shifts & Reconciliation",
            "shifts": "Shifts & Reconciliation",
            "audit-log": "Audit & Export",
            "exports": "Audit & Export",
            "dashboard": "Dashboard",
            "sidebar-counts": "Dashboard",
            "forecast": "Dashboard",
            "analytics": "Analytics",
            "staff": "Analytics",
            "ai": "AI Insights",
        }
        return root + ["Cloud Administration", labels.get(group, "Other")]
    if path.startswith("/auth/courier/"):
        return root + ["Courier Mobile", "Authentication"]
    if path.startswith("/courier/"):
        group = segment(path, "/courier/")
        labels = {
            "me": "Profile",
            "orders": "Orders",
            "stats": "Performance",
            "balance": "Money & Reconciliation",
            "notifications": "Notifications",
            "shift": "Shift & Location",
            "location": "Shift & Location",
            "push-token": "Notifications",
        }
        return root + ["Courier Mobile", labels.get(group, "Other")]
    if path.startswith("/orders/"):
        return root + ["Courier Mobile", "Order Actions"]
    if path.startswith("/payments/"):
        return root + ["Courier Mobile", "Payments"]
    return root + ["Other"]


def local_folders(path: str) -> list[str]:
    root = ["Local POS"]
    if path == "/healthz" or path.startswith("/api/licensing/"):
        return root + ["Health & Licensing"]
    if path.startswith("/api/sync/"):
        return root + ["Cloud Synchronization"]
    if path.startswith("/api/fiscalization/"):
        return root + ["Fiscalization"]
    if path.startswith("/api/qr/"):
        return root + ["Public QR Ordering"]
    if path.startswith("/api/cashbox/"):
        return root + ["Cashbox"]
    if path.startswith("/api/waiters/"):
        group = segment(path, "/api/waiters/")
        labels = {
            "auth-login": "Authentication",
            "auth-logout": "Authentication",
            "auth-me": "Authentication",
            "auth-change-password": "Authentication",
            "auth-sessions": "Authentication",
            "places": "Places & Tables",
            "tables": "Places & Tables",
            "orders": "Orders",
            "menu": "Menu",
            "stats": "Performance",
            "venue-config": "Configuration",
        }
        return root + ["Waiter POS", labels.get(group, "Other")]
    if path.startswith("/api/couriers"):
        return root + ["Cashier POS", "Courier Dispatch"]
    if path.startswith("/auth/courier/"):
        return root + ["Courier Mobile", "Authentication"]
    if path.startswith("/courier/"):
        group = segment(path, "/courier/")
        labels = {
            "me": "Profile",
            "orders": "Orders",
            "stats": "Performance",
            "balance": "Money & Reconciliation",
            "notifications": "Notifications",
            "shift": "Shift & Location",
            "location": "Shift & Location",
            "push-token": "Notifications",
        }
        return root + ["Courier Mobile", labels.get(group, "Other")]
    if re.fullmatch(r"/orders/:[^/]+/(accept|decline|status)/", path):
        return root + ["Courier Mobile", "Order Actions"]
    if path.startswith("/payments/"):
        return root + ["Courier Mobile", "Payments"]
    if path.startswith("/auth-"):
        return root + ["Cashier POS", "Authentication"]
    if path == "/cashiers":
        return root + ["Cashier POS", "Staff"]
    if path.startswith("/categories") or path.startswith("/products"):
        return root + ["Cashier POS", "Menu"]
    if path.startswith("/clients"):
        return root + ["Cashier POS", "Customers"]
    if path.startswith("/orders"):
        return root + ["Cashier POS", "Orders"]
    if path.startswith("/payment"):
        return root + ["Cashier POS", "Payments"]
    if path.startswith("/shifts"):
        return root + ["Cashier POS", "Shifts"]
    if path == "/couriers":
        return root + ["Cashier POS", "Courier Dispatch"]
    return root + ["Other"]


def route_auth(edition: str, path: str) -> tuple[str, list[dict[str, str]]]:
    """Return a human-readable auth contract and concrete Postman headers."""
    route = path.rstrip("/")
    if route == "/healthz" or route.endswith("/auth-login"):
        return "Public", []
    if route in {
        "/auth-login",
        "/auth/courier/login",
        "/auth/courier/refresh",
        "/auth/courier/revoke",
        "/payments/webhook",
        "/api/smartfood/auth",
        "/api/licensing/status",
        "/api/licensing/setup",
        "/api/licensing/plans",
        "/api/sync/health",
        "/cashiers",
    } or route.startswith("/api/qr/"):
        if route == "/payments/webhook":
            return (
                "Courier payment webhook shared secret",
                [{"key": "X-Webhook-Secret", "value": "{{paymentWebhookSecret}}"}],
            )
        return "Public", []
    if route == "/api/customer-bot/webhook":
        return (
            "Telegram webhook secret",
            [
                {
                    "key": "X-Telegram-Bot-Api-Secret-Token",
                    "value": "{{telegramWebhookSecret}}",
                }
            ],
        )
    if route.startswith("/api/sync/"):
        if route in {"/api/sync/receive", "/api/sync/changes", "/api/sync/shift-close/ack"}:
            note = "Branch credential and branch identity"
            headers = [
                {"key": "Authorization", "value": "Branch {{branchToken}}"},
                {"key": "X-Branch-ID", "value": "{{branchId}}"},
            ]
            if edition == "local" and route == "/api/sync/receive":
                note = "Cloud credential when the cloud pushes changes to local"
                headers[0]["value"] = "Cloud {{cloudSyncToken}}"
            return note, headers
        return (
            "Management credential",
            [{"key": "Authorization", "value": "Management {{managementToken}}"}],
        )
    if route.startswith("/api/smartfood/"):
        return (
            "SmartFood customer bearer token",
            [{"key": "Authorization", "value": "Bearer {{customerToken}}"}],
        )
    if (
        route.startswith("/auth/courier/")
        or route.startswith("/courier/")
        or route.startswith("/payments/")
        or (
            edition == "cloud"
            and re.fullmatch(r"/orders/:[^/]+/(accept|decline|status)", route)
        )
        or (
            edition == "local"
            and path.endswith("/")
            and re.fullmatch(r"/orders/:[^/]+/(accept|decline|status)", route)
        )
    ):
        return (
            "Courier bearer token",
            [{"key": "Authorization", "value": "Bearer {{courierToken}}"}],
        )
    if edition == "cloud":
        return (
            "Cloud administrator bearer token",
            [{"key": "Authorization", "value": "Bearer {{adminToken}}"}],
        )
    if route.startswith("/api/waiters/"):
        return (
            "Waiter bearer token",
            [{"key": "Authorization", "value": "Bearer {{waiterToken}}"}],
        )
    return (
        "Local POS bearer token",
        [{"key": "Authorization", "value": "Bearer {{posToken}}"}],
    )


def query_parameters(path: str, method: str) -> list[tuple[str, str, str]]:
    path = path.rstrip("/")
    if path == "/api/sync/queue/clear":
        return [("confirm", "true", "Required destructive-operation confirmation")]
    if method != "GET":
        return []
    params: list[tuple[str, str, str]] = []
    if (
        path.startswith("/api/admins/orders/stats")
        or path.startswith("/api/admins/dashboard")
        or path.startswith("/api/admins/analytics")
        or path.startswith("/api/admins/staff/performance")
        or path.startswith("/api/admins/forecast")
        or path.startswith("/api/admins/audit-log")
        or path.startswith("/api/admins/exports/")
        or path.startswith("/api/admins/inkassa/")
        or path.startswith("/api/admins/treasury/history")
        or path.startswith("/api/admins/hr/expenses/stats")
        or path.startswith("/api/admins/hr/attendance/")
    ):
        params.extend(
            [
                ("from_at", "{{fromAt}}", "Inclusive ISO-8601 reporting start"),
                ("to_at", "{{toAt}}", "Exclusive ISO-8601 reporting end"),
            ]
        )
    elif any(
        path.endswith(marker)
        for marker in (
            "/orders",
            "/products",
            "/customers",
            "/users",
            "/expenses",
            "/employees",
            "/transactions",
            "/logs",
            "/queue",
            "/shifts",
            "/couriers",
            "/tickets",
        )
    ):
        params.extend(
            [
                ("page", "{{page}}", "1-based page"),
                ("per_page", "{{perPage}}", "Page size"),
            ]
        )
    if path in {"/clients", "/clients/lookup"}:
        params = [("phone", "{{phone}}", "Customer phone lookup")]
    if path.endswith("/search"):
        params.append(("q", "{{search}}", "Search text"))
    if path == "/api/sync/changes":
        params = [
            ("since", "{{fromAt}}", "Return changes after this cursor/time"),
            ("page", "{{page}}", "1-based page"),
            ("per_page", "{{perPage}}", "Page size"),
        ]
    if path == "/api/sync/shift-close/ack":
        params = [
            ("shift_uuid", "{{shiftUuid}}", "Canonical shift UUID"),
            ("manifest_version", "1", "Positive manifest version"),
            (
                "manifest_digest",
                "{{manifestDigest}}",
                "64-character SHA-256 manifest digest",
            ),
        ]
    if path.endswith("/geo/reverse"):
        params = [
            ("lat", "{{latitude}}", "Latitude"),
            ("lng", "{{longitude}}", "Longitude"),
        ]
    if path.endswith("/geo/forward"):
        params = [("q", "{{addressQuery}}", "Address search")]
    if path == "/api/smartfood/catalog/categories":
        params = [("lang", "uz", "Response language")]
    if path == "/api/smartfood/catalog/products":
        params = [
            ("category_id", "{{categoryId}}", "Optional category filter"),
            ("q", "{{search}}", "Optional product search"),
            ("lang", "uz", "Response language"),
        ]
    if path == "/api/fiscalization/receipts":
        params = [("status", "PENDING", "Optional fiscal receipt status")]
    return params


def body_example(edition: str, path: str, method: str) -> dict[str, Any] | None:
    courier_order_action = path.startswith("/orders/") and path.endswith("/")
    path = path.rstrip("/")
    if method not in MUTATION_METHODS:
        return None
    bodyless = {
        "/api/admins/auth-logout",
        "/api/admins/auth-logout-all",
        "/auth-logout",
        "/auth-logout-all",
        "/api/waiters/auth-logout",
        "/api/smartfood/auth/logout",
        "/auth/courier/logout",
        "/api/admins/orders/:order_id/unpay",
        "/api/fiscalization/test",
    }
    if path in bodyless or any(
        path.endswith(suffix)
        for suffix in (
            "/set-default",
            "/auto-consume",
            "/variance-codes/seed",
            "/queue/process",
            "/queue/clear",
            "/ai/chats/:chat_id/delete",
            "/auth/logout",
            "/request-payment",
            "/remove-discount",
            "/documents/:doc_id/verify",
            "/reviews/:review_id/submit",
            "/reviews/:review_id/acknowledge",
            "/config/enable",
            "/accept",
            "/resume",
            "/addresses/:address_id/default",
        )
    ):
        return None
    if path in {"/api/admins/auth-login", "/auth-login"}:
        prefix = "admin" if edition == "cloud" else "pos"
        return {"email": "{{" + prefix + "Email}}", "password": "{{" + prefix + "Password}}"}
    if path == "/api/waiters/auth-login":
        return {"email": "{{waiterEmail}}", "password": "{{waiterPassword}}"}
    if path == "/auth/courier/login":
        return {"phone": "{{courierPhone}}", "password": "{{courierPassword}}"}
    if path == "/auth/courier/refresh":
        return {"refresh_token": "{{courierRefreshToken}}"}
    if path == "/auth/courier/revoke":
        return {"refresh_token": "{{courierRefreshToken}}"}
    if path == "/api/smartfood/auth":
        return {"init_data": "{{telegramInitData}}"}
    if path.endswith("/auth-change-password"):
        return {"current_password": "change-me", "new_password": "replace-before-send"}
    if path == "/api/sync/receive":
        return {
            "batch_id": "postman-example-batch",
            "branch_id": "{{branchId}}",
            "changes": [],
        }
    if path == "/api/sync/shift-close/ack":
        return {
            "shift_uuid": "{{shiftUuid}}",
            "manifest_version": 1,
            "manifest_digest": "replace-with-64-character-sha256-manifest-digest",
        }
    if path in {"/api/sync/trigger", "/api/sync/trigger-pull", "/api/sync/full-push"}:
        return {"branch_id": "{{branchId}}", "reason": "Manual Postman request"}
    if path == "/api/licensing/setup":
        return {"email": "{{adminEmail}}", "plan_id": "{{planId}}"}
    if path == "/api/licensing/plan-change":
        return {"plan_id": "{{planId}}", "note": "Postman example plan change"}
    if path == "/api/fiscalization/mode":
        return {"mode": "test"}
    if path == "/api/fiscalization/retry":
        return {"receipt_id": "{{receiptId}}"}
    if path.endswith("/fiscalize"):
        return {"order_id": "{{orderId}}", "mode": "test"}
    if path == "/api/customer-bot/webhook":
        return {
            "update_id": 1,
            "message": {
                "message_id": 1,
                "chat": {"id": 1, "type": "private"},
                "text": "/start",
            },
        }
    if path.endswith("/orders/create") or path in {"/orders/create", "/api/smartfood/orders"}:
        return {
            "order_type": "DINE_IN",
            "table_id": "{{tableId}}",
            "customer_id": "{{customerId}}",
            "items": [{"product_id": "{{productId}}", "quantity": 1}],
            "idempotency_key": "postman-example-order",
        }
    if path.endswith("/cart/quote"):
        return {
            "items": [{"product_id": "{{productId}}", "quantity": 1}],
            "delivery_address_id": "{{addressId}}",
        }
    if path.endswith("/add-item"):
        return {"product_id": "{{productId}}", "quantity": 1}
    if "/items/" in path and method in {"PATCH", "PUT"}:
        return {"quantity": 2, "notes": "Postman example"}
    if path.endswith("/pay"):
        return {
            "payment_method": "CASH",
            "amount_received": "{{amount}}",
            "currency": "{{currency}}",
        }
    if path == "/payments/create":
        return {
            "order_id": "{{orderId}}",
            "amount": "{{amount}}",
            "currency": "{{currency}}",
            "provider": "CASH",
            "idempotency_key": "postman-example-payment",
        }
    if path == "/payments/webhook":
        return {
            "external_id": "provider-example-1",
            "payment_id": "{{paymentId}}",
            "order_id": "{{orderId}}",
            "provider": "QR",
            "status": "PAID",
            "amount": "{{amount}}",
        }
    if path.endswith("/refund"):
        return {"amount": "{{amount}}", "reason": "Postman test refund"}
    if path.endswith("/status"):
        if courier_order_action:
            return {"step": "DELIVERED"}
        return {"status": "READY"}
    if path.endswith("/details"):
        return {"customer_id": "{{customerId}}", "notes": "Postman example"}
    if path.endswith("/courier") or path.endswith("/couriers/assign") or path.endswith(
        "/couriers/assign"
    ):
        return {"order_id": "{{orderId}}", "courier_id": "{{courierId}}"}
    if path.endswith("/inkassa/perform"):
        return {
            "cash": "{{amount}}",
            "uzcard": "0.00",
            "humo": "0.00",
            "card": "0.00",
            "payme": "0.00",
            "notes": "Counted and confirmed by manager",
            "idempotency_key": "postman-example-inkassa",
        }
    if path.endswith("/treasury/transfer"):
        return {
            "from": "CASH_REGISTER",
            "to": "SAFE",
            "amount": "{{amount}}",
            "description": "Postman example transfer",
        }
    if path.endswith("/treasury/expense"):
        return {
            "account": "CASH_REGISTER",
            "amount": "{{amount}}",
            "category": "OPERATING",
            "description": "Postman example expense",
        }
    if path == "/api/admins/shifts/start":
        return {
            "user_id": "{{userId}}",
            "shift_template_id": "{{templateId}}",
            "branch_id": "{{branchId}}",
        }
    if path.endswith("/shifts/start") or path == "/shifts/start":
        return {"shift_template_id": "{{templateId}}"}
    if path.endswith("/shifts/end") or path == "/shifts/end":
        return {
            "notes": "Verified closing count",
            "counted": {
                "CASH": "{{amount}}",
                "UZCARD": "0.00",
                "HUMO": "0.00",
                "PAYME": "0.00",
            },
        }
    if path.startswith("/shifts/") and path.endswith("/end"):
        return {
            "notes": "Manager-assisted close after a physical tender count",
            "counted": {
                "CASH": "{{amount}}",
                "UZCARD": "0.00",
                "HUMO": "0.00",
                "CARD": "0.00",
                "PAYME": "0.00",
            },
        }
    if path.startswith("/api/admins/shifts/") and path.endswith("/end"):
        return {
            "notes": "Verified closing count",
            "counted": {
                "CASH": "{{amount}}",
                "UZCARD": "0.00",
                "HUMO": "0.00",
                "CARD": "0.00",
                "PAYME": "0.00",
            },
        }
    if path.endswith("/reconcile"):
        return {
            "actual_cash": "{{amount}}",
            "confirmed": {
                "CASH": "{{amount}}",
                "UZCARD": "0.00",
                "HUMO": "0.00",
                "CARD": "0.00",
                "PAYME": "0.00",
            },
            "notes": "Manager independently counted physical cash",
        }
    if path.endswith("/expenses"):
        return {
            "category_id": "{{categoryId}}",
            "amount": "{{amount}}",
            "recipient_supplier_id": "{{supplierId}}",
            "comment": "Postman example expense",
        }
    if path.endswith("/apply-discount"):
        return {"discount_id": "{{discountId}}"}
    if path.endswith("/check-secret-word") or path.endswith("/secret-word"):
        return {"secret_word": "replace-before-send"}
    if path.endswith("/print-jobs/claim"):
        return {"device_id": "{{deviceId}}"}
    if "/print-jobs/" in path:
        return {"device_id": "{{deviceId}}", "message": "Printer result"}
    if path == "/api/qr/order/:token":
        return {
            "table_id": "{{tableId}}",
            "items": [{"product_id": "{{productId}}", "quantity": 1}],
        }
    if path.endswith("/location"):
        return {"latitude": "{{latitude}}", "longitude": "{{longitude}}"}
    if path.endswith("/shift/online"):
        return {"online": True}
    if path.endswith("/shift/share-location"):
        return {"enabled": True}
    if path.endswith("/shift/settle"):
        return {"bonuses": "0.00", "tips": "0.00", "note": "Postman example settlement"}
    if path.endswith("/push-token"):
        return {"token": "replace-with-device-push-token", "platform": "android"}
    if path.endswith("/notifications/read"):
        return {"notification_ids": ["{{notificationId}}"]}
    if path.endswith("/create") and "courier" in path:
        return {
            "name": "Example Courier",
            "phone": "{{courierPhone}}",
            "password": "{{courierPassword}}",
        }
    if path.endswith("/regenerate"):
        return {"reason": "Credential rotation"}
    if path.endswith("/redeem"):
        return {"points": 100, "idempotency_key": "postman-example-redemption"}
    if path.endswith("/loyalty/scan"):
        return {"phone": "{{phone}}", "order_id": "{{orderId}}"}
    if path.endswith("/loyalty/grant"):
        return {"phone": "{{phone}}", "points": 100, "reason": "Postman example"}
    if path.endswith("/loyalty/fulfill"):
        return {"redemption_id": "{{redemptionId}}"}
    if path.endswith("/addresses"):
        return {
            "label": "Example address",
            "address": "{{addressQuery}}",
            "latitude": "{{latitude}}",
            "longitude": "{{longitude}}",
        }
    if path.startswith("/api/smartfood/addresses/"):
        return {
            "label": "Example address",
            "address": "{{addressQuery}}",
            "latitude": "{{latitude}}",
            "longitude": "{{longitude}}",
        }
    if path.endswith("/messages"):
        return {"message": "Example support reply"}
    if path.endswith("/dismiss"):
        return {"until": "{{toAt}}"}
    if path.endswith("/ack"):
        return {"note": "Reviewed in Postman"}
    if path.endswith("/reorder"):
        return {"ordered_ids": ["{{categoryId}}"]}
    if path.endswith("/bulk-delete") or path.endswith("/bulk-restore"):
        return {"ids": ["{{categoryId}}"]}
    if path.endswith("/toggle"):
        return {"enabled": True}
    if path.endswith("/cancel"):
        return {"reason": "Postman example cancellation"}
    if path.endswith("/decline") or path.endswith("/stop"):
        return {"reason": "Postman example reason"}
    if path.endswith("/ready") or path.endswith("/unready") or path.endswith("/restore"):
        return {"notes": "Postman example action"}
    if path.endswith("/approve") or path.endswith("/reject"):
        return {"notes": "Reviewed in Postman"}
    if path.endswith("/activate") or path.endswith("/terminate") or path.endswith("/renew"):
        return {"effective_date": "{{fromDate}}", "notes": "Postman example"}
    if path.endswith("/check-in") or path.endswith("/check-out"):
        return {"employee_id": "{{employeeId}}", "occurred_at": "{{fromAt}}"}
    if path.endswith("/progress"):
        return {"progress": 50, "notes": "Postman example"}
    if path.endswith("/adjust"):
        return {
            "item_id": "{{itemId}}",
            "location_id": "{{locationId}}",
            "quantity": 1,
            "reason": "Postman example adjustment",
        }
    if path.endswith("/units/convert"):
        return {
            "quantity": 1,
            "from_unit_id": "{{unitId}}",
            "to_unit_id": "{{destinationUnitId}}",
        }
    if "/batches/" in path and path.endswith("/consume"):
        return {"quantity": 1, "location_id": "{{locationId}}"}
    if "/purchase-order-items/" in path:
        return {"quantity": 1, "unit_price": "{{amount}}"}
    if "/recipe-ingredients/" in path:
        return {"quantity": 1, "unit_id": "{{unitId}}"}
    if path.endswith("/reserve") or path.endswith("/release-reservation"):
        return {"item_id": "{{itemId}}", "quantity": 1, "reference": "{{orderId}}"}
    if "/transfers" in path:
        return {
            "from_location_id": "{{locationId}}",
            "to_location_id": "{{destinationLocationId}}",
            "items": [{"item_id": "{{itemId}}", "quantity": 1}],
        }
    if "/purchase-orders" in path or "/receiving" in path:
        return {
            "supplier_id": "{{supplierId}}",
            "location_id": "{{locationId}}",
            "items": [{"item_id": "{{itemId}}", "quantity": 1}],
        }
    if "/recipes" in path:
        return {"name": "Example recipe", "yield_quantity": 1, "unit_id": "{{unitId}}"}
    if "/production-orders/" in path and path.endswith("/:action"):
        return {"notes": "Postman example production action"}
    if "/counts/" in path and path.endswith("/record"):
        return {
            "item_id": "{{itemId}}",
            "counted_quantity": 1,
            "variance_code_id": "{{codeId}}",
        }
    if "/counts/" in path and path.endswith("/:action"):
        return {"notes": "Postman example count action"}
    if path.endswith("/link-recipe"):
        return {"recipe_id": "{{recipeId}}"}
    if path.endswith("/link-item"):
        return {"item_id": "{{itemId}}", "quantity": 1}
    if path.endswith("/link-components"):
        return {"components": [{"item_id": "{{itemId}}", "quantity": 1}]}
    if path.endswith("/orders/deduct") or path.endswith("/orders/reverse"):
        return {"order_id": "{{orderId}}"}
    if path.endswith("/orders/check-availability"):
        return {
            "items": [{"product_id": "{{productId}}", "quantity": 1}],
            "location_id": "{{locationId}}",
        }
    if path.endswith("/ai/query"):
        return {"query": "Which items are below reorder level?"}
    if path.endswith("/rename"):
        return {"name": "Example chat"}
    if path.endswith("/salaries/generate"):
        return {"period": "{{fromDate}}", "employee_ids": ["{{employeeId}}"]}
    if path.endswith("/salaries/approve-all"):
        return {"period": "{{fromDate}}", "notes": "Reviewed in Postman"}
    if path.endswith("/base") and "/salaries/" in path:
        return {"base_amount": "{{amount}}"}
    if path.endswith("/deductions") and "/salaries/" in path:
        return {"amount": "{{amount}}", "reason": "Postman example deduction"}
    if path.endswith("/cash/deposit") or path.endswith("/cash/withdraw"):
        return {"amount": "{{amount}}", "description": "Postman example HR cash movement"}
    if path.endswith("/leave-balances/initialize"):
        return {"employee_id": "{{employeeId}}", "year": 2026}
    if path.endswith("/discounts/validate"):
        return {"code": "EXAMPLE10", "order_subtotal": "{{amount}}"}
    if path.endswith("/discounts/apply"):
        return {"order_id": "{{orderId}}", "discount_code": "EXAMPLE10"}
    if path.endswith("/discounts/remove"):
        return {"order_id": "{{orderId}}", "order_discount_id": "{{orderDiscountId}}"}
    if path.endswith("/notifications/settings/test"):
        return {"type": "shift_closed", "recipient": "{{phone}}"}
    if "/notifications/types/" in path:
        return {"enabled": True}
    if path.endswith("/preview") and "/notifications/templates/" in path:
        return {"context": {"customer_name": "Example Customer"}}
    if path.endswith("/orders/:bot_order_id/dispatch"):
        return {"cashier_id": "{{userId}}"}
    if path.endswith("/orders/:bot_order_id/reject"):
        return {"reason": "Postman example rejection"}
    if path.startswith("/api/admins/smartfood/products/") and method == "PATCH":
        return {"name": "Example product", "price": "{{amount}}"}
    if path.startswith("/api/admins/smartfood/categories/") and method == "PATCH":
        return {"name": "Example category"}
    if path.endswith("/sizes"):
        return {"name": "Large", "price_delta": "5000.00"}
    if path.endswith("/topping-groups"):
        return {"name": "Extras", "min_select": 0, "max_select": 2}
    if path.endswith("/toppings"):
        return {"name": "Example topping", "price": "5000.00"}
    if "/smartfood/sizes/" in path:
        return {"name": "Large", "price_delta": "5000.00"}
    if "/smartfood/topping-groups/" in path:
        return {"name": "Extras", "max_select": 2}
    if "/smartfood/toppings/" in path:
        return {"name": "Example topping", "price": "5000.00"}
    if path.endswith("/type"):
        return {"order_type": "TAKEAWAY"}
    if path.startswith("/api/admins/customers/"):
        return {"name": "Example Customer", "phone": "{{customerPhone}}"}
    if method in {"PATCH", "PUT"}:
        return {"notes": "Example update — replace fields before sending"}
    return {"notes": "Example action — review endpoint fields before sending"}


def capture_script(edition: str, path: str, method: str) -> list[str]:
    path = path.rstrip("/")
    captures: list[tuple[str, tuple[str, ...]]] = []
    if path == "/api/admins/auth-login":
        captures.extend(
            [
                ("adminToken", ("data.token", "token", "data.access", "access")),
                ("sessionToken", ("data.token", "token", "data.access", "access")),
                ("userId", ("data.user.id", "user.id", "data.id")),
            ]
        )
    elif path == "/auth-login":
        captures.extend(
            [
                ("posToken", ("data.token", "token", "data.access", "access")),
                ("sessionToken", ("data.token", "token", "data.access", "access")),
                ("userId", ("data.user.id", "user.id", "data.id")),
            ]
        )
    elif path == "/api/waiters/auth-login":
        captures.extend(
            [
                ("waiterToken", ("data.token", "token", "data.access", "access")),
                ("sessionToken", ("data.token", "token", "data.access", "access")),
                ("userId", ("data.user.id", "user.id", "data.id")),
            ]
        )
    elif path == "/auth/courier/login":
        captures.extend(
            [
                ("courierToken", ("data.access", "access", "data.token", "token")),
                (
                    "courierRefreshToken",
                    ("data.refresh_token", "refresh_token", "data.refresh", "refresh"),
                ),
                ("courierId", ("data.courier.id", "courier.id", "data.id")),
            ]
        )
    elif path == "/api/smartfood/auth":
        captures.extend(
            [
                ("customerToken", ("data.token", "token", "data.access", "access")),
                ("customerId", ("data.customer.id", "customer.id", "data.id")),
            ]
        )
    elif method == "POST" and (
        path.endswith("/orders/create") or path in {"/orders/create", "/api/smartfood/orders"}
    ):
        captures.append(("orderId", ("data.order.id", "order.id", "data.id", "id")))
    elif method == "POST" and (path.endswith("/shifts/start") or path == "/shifts/start"):
        captures.append(("shiftId", ("data.shift.id", "shift.id", "data.id", "id")))
    elif method == "POST" and "courier" in path and path.endswith("/create"):
        captures.append(("courierId", ("data.courier.id", "courier.id", "data.id", "id")))
    elif method == "GET" and "/notifications/qr/tables/" in path:
        captures.append(("qrToken", ("data.token", "token")))
    elif method == "POST" and path.endswith("/print-jobs/claim"):
        captures.append(("claimToken", ("data.claim_token", "claim_token", "data.token", "token")))

    if not captures:
        return []
    lines = [
        "if (pm.response.code >= 200 && pm.response.code < 300) {",
        "  let payload = {};",
        "  try { payload = pm.response.json(); } catch (e) { payload = {}; }",
        "  const pick = (obj, dotted) => dotted.split('.').reduce((v, k) => "
        "(v === null || v === undefined ? undefined : v[k]), obj);",
    ]
    for variable, candidates in captures:
        array = json.dumps(list(candidates))
        lines.extend(
            [
                f"  const {variable} = {array}.map(p => pick(payload, p)).find(v => v !== undefined && v !== null && v !== '');",
                f"  if ({variable} !== undefined) pm.collectionVariables.set('{variable}', String({variable}));",
            ]
        )
    lines.append("}")
    return lines


def build_request(
    edition: str,
    path: str,
    source_items: list[dict[str, Any]],
    variables: set[str],
) -> dict[str, Any]:
    methods = list(OrderedDict.fromkeys(item["request"]["method"] for item in source_items))
    method = next((candidate for candidate in METHOD_PRIORITY if candidate in methods), methods[0])
    representative = next(item for item in source_items if item["request"]["method"] == method)
    display_path, discovered = postman_path(path)
    variables.update(discovered)
    base = "cloudBaseUrl" if edition == "cloud" else "localBaseUrl"
    auth_note, headers = route_auth(edition, path)
    headers = [dict(header) for header in headers]
    if path.rstrip("/") == "/api/admins/inkassa/perform":
        headers.append({"key": "Idempotency-Key", "value": "{{idempotencyKey}}"})
    body = body_example(edition, path, method)
    if body is not None:
        headers.append({"key": "Content-Type", "value": "application/json"})
    query = query_parameters(path, method)
    query_string = ""
    if query:
        query_string = "?" + "&".join(f"{key}={value}" for key, value, _ in query)
    method_list = ", ".join(methods)
    alternate = ""
    if len(methods) > 1:
        alternate = (
            "\n\nThis registered path accepts multiple methods. This item uses the "
            f"safe representative **{method}** method; supported methods: **{method_list}**. "
            "Duplicate path items are intentionally avoided."
        )
    query_doc = ""
    if query:
        query_doc = "\n\nExample query parameters:\n" + "\n".join(
            f"- `{key}` — {description}" for key, _, description in query
        )
    operational_note = ""
    if path.rstrip("/") == "/api/customer-bot/webhook":
        operational_note = (
            "\n\n**License behavior:** the mounted customer-bot webhook is explicitly "
            "allowed through license blocking so Telegram updates can still be "
            "acknowledged instead of being retried indefinitely."
        )
    description = (
        f"**Edition:** {'cloud server' if edition == 'cloud' else 'local POS'}  \n"
        f"**Registered route:** `{path}`  \n"
        f"**Authentication:** {auth_note}  \n"
        f"**Allowed methods:** {method_list}"
        f"{alternate}{query_doc}{operational_note}\n\n"
        "Replace example values and identifiers before sending a mutating request."
    )
    request: dict[str, Any] = {
        "method": method,
        "header": headers,
        "url": f"{{{{{base}}}}}{display_path}{query_string}",
        "description": description,
    }
    if body is not None:
        request["body"] = {
            "mode": "raw",
            "raw": json.dumps(body, indent=2, ensure_ascii=False),
            "options": {"raw": {"language": "json"}},
        }
    display_name = title_case_name(representative["name"])
    if edition == "cloud" and path == "/api/admins/analytics/comparison/":
        display_name += " — Trailing-Slash Alias"
    elif edition == "local" and path == "/clients/lookup":
        display_name += " — Explicit Lookup Alias"
    item: dict[str, Any] = {
        "name": f"[{method}] {display_name}",
        "request": request,
    }
    script = capture_script(edition, path, method)
    if script:
        item["event"] = [
            {
                "listen": "test",
                "script": {"type": "text/javascript", "exec": script},
            }
        ]
    return item


def insert_folder(tree: OrderedDict[str, Any], folders: list[str], item: dict[str, Any]) -> None:
    cursor = tree
    for folder in folders:
        cursor = cursor.setdefault(folder, OrderedDict())
    cursor.setdefault("__items__", []).append(item)


def materialize_tree(tree: OrderedDict[str, Any], depth: int = 0) -> list[dict[str, Any]]:
    result: list[dict[str, Any]] = []
    for name, value in tree.items():
        if name == "__items__":
            result.extend(value)
            continue
        folder: dict[str, Any] = {"name": name, "item": materialize_tree(value, depth + 1)}
        if depth == 0:
            folder["description"] = (
                "Requests are grouped by the deployed edition. HTTP routes come directly "
                "from Django's resolver; realtime routes come from the edition's ASGI router."
            )
        result.append(folder)
    return result


def websocket_item(name: str, url: str, edition: str) -> dict[str, Any]:
    auth_note = (
        "The URL includes the expected `?token=` transport because a cookie alone "
        "does not authenticate the cloud consumers."
        if edition == "cloud"
        else "The URL includes an explicit token. Local OPEN_LAN may trust the three "
        "in-store streams, but the courier stream still requires courier identity."
    )
    return {
        "name": f"[WS] {name}",
        "request": {
            "method": "GET",
            "header": [],
            "url": url,
            "description": (
                f"Registered {'cloud server' if edition == 'cloud' else 'local POS'} "
                "ASGI WebSocket route. Postman supports WebSocket requests through its "
                f"New → WebSocket flow; copy this URL there. {auth_note}"
            ),
        },
    }


def initial_variables(discovered: set[str]) -> list[dict[str, str]]:
    values = OrderedDict(BASE_VARIABLES)
    for name in sorted(discovered):
        if name in values:
            continue
        if name in ID_DEFAULTS:
            value = ID_DEFAULTS[name]
        elif name.lower().endswith("token"):
            value = ""
        elif name.lower().endswith("id"):
            value = "1"
        elif name == "roleName":
            value = "cashier"
        elif name == "documentKind":
            value = "contract"
        else:
            value = "sample"
        values[name] = value
    return [{"key": key, "value": value, "type": "string"} for key, value in values.items()]


def build_collection(server_raw: Path, local_raw: Path) -> tuple[dict[str, Any], dict[str, int]]:
    source_docs = {
        "cloud": json.loads(server_raw.read_text(encoding="utf-8")),
        "local": json.loads(local_raw.read_text(encoding="utf-8")),
    }
    tree: OrderedDict[str, Any] = OrderedDict()
    variables: set[str] = set()
    stats: dict[str, int] = {}
    for edition, source in source_docs.items():
        grouped = source_groups(edition, source)
        stats[f"{edition}_method_requests"] = sum(len(items) for items in grouped.values())
        stats[f"{edition}_distinct_paths"] = len(grouped)
        for path, source_items in grouped.items():
            folders = cloud_folders(path) if edition == "cloud" else local_folders(path)
            insert_folder(
                tree,
                folders,
                build_request(edition, path, source_items, variables),
            )
        ws_folder = ["Cloud Server" if edition == "cloud" else "Local POS", "Realtime WebSockets"]
        for name, url in WEBSOCKETS[edition]:
            insert_folder(tree, ws_folder, websocket_item(name, url, edition))
        stats[f"{edition}_websockets"] = len(WEBSOCKETS[edition])

    total_http = stats["cloud_distinct_paths"] + stats["local_distinct_paths"]
    description = f"""# Alpha POS API

Import-ready Postman Collection v2.1 for the deployed Alpha POS cloud server and
local POS editions.

## Coverage

- **{stats['cloud_distinct_paths']}** distinct cloud HTTP paths
- **{stats['local_distinct_paths']}** distinct local HTTP paths
- **{total_http}** edition/path HTTP entries in total
- **{stats['cloud_websockets']}** cloud and **{stats['local_websockets']}** local ASGI WebSocket routes

Each distinct registered HTTP path appears exactly once per deployed edition.
For multi-method Django views, the item description lists every allowed method
and the request uses one representative method. Django's generated `/admin/`
HTML application and the standalone core test URLconf are deliberately excluded.

## Safety and setup

All hosts, credentials, phone numbers, UUIDs and IDs are placeholders. No
production key or customer record is embedded. Set the collection variables for
the environment you intend to test, run the relevant login request, and inspect
every example body before sending mutations. Login/create tests only capture
authoritative token or ID fields when a successful JSON response supplies them.

## Synchronization authentication

Branch replication uses `Branch {{{{branchToken}}}}` plus `X-Branch-ID`;
cloud-to-local receive uses `Cloud {{{{cloudSyncToken}}}}`; management controls
use `Management {{{{managementToken}}}}`. Trigger, trigger-pull, full-push, and
the Cloud form of `/api/sync/receive` are local-only behavior gates; shift-close
acknowledgement is cloud-only. All eleven shared URL patterns are still
registered by both editions.
"""
    collection = {
        "info": {
            "_postman_id": str(uuid.UUID("a1fa66fb-c18d-4c13-8e3e-5481f86ddf55")),
            "name": "Alpha POS — Cloud, Local POS & Realtime API",
            "description": description,
            "schema": SCHEMA,
        },
        "variable": initial_variables(variables),
        "event": [
            {
                "listen": "test",
                "script": {
                    "type": "text/javascript",
                    "exec": [
                        "pm.test('Response is not an unhandled server error', function () {",
                        "  pm.expect(pm.response.code).to.not.eql(500);",
                        "});",
                    ],
                },
            }
        ],
        "item": materialize_tree(tree),
    }
    stats["http_total"] = total_http
    stats["websocket_total"] = stats["cloud_websockets"] + stats["local_websockets"]
    return collection, stats


def validate_coverage(
    collection: dict[str, Any], server_raw: Path, local_raw: Path
) -> list[str]:
    errors: list[str] = []
    final_items = flatten(collection["item"])
    http_items = [
        item
        for item in final_items
        if not item["name"].startswith("[WS]")
    ]
    final_by_edition: dict[str, list[str]] = {"cloud": [], "local": []}
    for item in http_items:
        url = raw_url(item)
        if url.startswith("{{cloudBaseUrl}}"):
            final_by_edition["cloud"].append(
                url.replace("{{cloudBaseUrl}}", "").split("?", 1)[0]
            )
        elif url.startswith("{{localBaseUrl}}"):
            final_by_edition["local"].append(
                url.replace("{{localBaseUrl}}", "").split("?", 1)[0]
            )
        else:
            errors.append(f"HTTP request has no edition base variable: {url}")

    for edition, raw_path in (("cloud", server_raw), ("local", local_raw)):
        source = json.loads(raw_path.read_text(encoding="utf-8"))
        expected: dict[str, set[str]] = {}
        for source_route, source_items in source_groups(edition, source).items():
            path, _ = postman_path(source_route)
            expected[path] = {
                item["request"]["method"] for item in source_items
            }
        actual = final_by_edition[edition]
        if len(actual) != len(set(actual)):
            errors.append(f"{edition}: duplicate HTTP path entries in final collection")
        missing = set(expected) - set(actual)
        extra = set(actual) - set(expected)
        if missing:
            errors.append(f"{edition}: missing paths: {sorted(missing)}")
        if extra:
            errors.append(f"{edition}: unexpected paths: {sorted(extra)}")
        base = "{{cloudBaseUrl}}" if edition == "cloud" else "{{localBaseUrl}}"
        selected = {
            raw_url(item).replace(base, "").split("?", 1)[0]: item["request"]["method"]
            for item in http_items
            if raw_url(item).startswith(base)
        }
        for path, method in selected.items():
            if path in expected and method not in expected[path]:
                errors.append(
                    f"{edition}: selected {method} is not allowed for {path}; "
                    f"expected {sorted(expected[path])}"
                )

    declared = {variable["key"] for variable in collection.get("variable", [])}
    serialized = json.dumps(collection, ensure_ascii=False)
    referenced = set(re.findall(r"\{\{([A-Za-z_][A-Za-z0-9_]*)\}\}", serialized))
    undeclared = referenced - declared
    if undeclared:
        errors.append(f"undeclared Postman variables: {sorted(undeclared)}")
    return errors


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--server-raw", type=Path, default=DEFAULT_SERVER_RAW)
    parser.add_argument("--local-raw", type=Path, default=DEFAULT_LOCAL_RAW)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()
    for source in (args.server_raw, args.local_raw):
        if not source.is_file():
            parser.error(f"missing resolver inventory: {source}")
    collection, stats = build_collection(args.server_raw, args.local_raw)
    errors = validate_coverage(collection, args.server_raw, args.local_raw)
    if errors:
        for error in errors:
            print(f"ERROR: {error}")
        return 1
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(
        json.dumps(collection, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    print(
        "Wrote "
        f"{stats['http_total']} HTTP route entries and "
        f"{stats['websocket_total']} WebSocket references to {args.output}"
    )
    print(
        f"Cloud: {stats['cloud_method_requests']} method requests -> "
        f"{stats['cloud_distinct_paths']} distinct paths; "
        f"local: {stats['local_method_requests']} method requests -> "
        f"{stats['local_distinct_paths']} distinct paths."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
