#!/usr/bin/env bash
#
# One-shot deploy for the Alpha POS SERVER edition (cloud back-office).
#
#   ./deploy.sh <SERVER_PUBLIC_IP>
#
# Idempotent — re-run to update (pulls code + the core submodule, rebuilds, keeps
# secrets + certs). Assumes Linux + Docker. Serves behind Caddy with automatic
# HTTPS via nip.io (no domain needed). The core spine is a git submodule, so the
# FIRST checkout must be `git clone --recurse-submodules` (this script also runs
# `submodule update --init` defensively).
set -euo pipefail

IP="${1:?Usage: ./deploy.sh <SERVER_PUBLIC_IP>}"
DIR="$(cd "$(dirname "$0")" && pwd)"
HOST="pos.${IP}.nip.io"
CONTROL_URL="${LICENSE_CONTROL_CENTER_URL:-https://control.${IP}.nip.io}"

echo ">> Alpha POS server  ->  https://${HOST}"

# --- 1. latest code + core submodule --------------------------------------
git -C "$DIR" pull --ff-only 2>/dev/null || echo "   (not a fast-forwardable checkout — skipping pull)"
git -C "$DIR" submodule update --init --recursive
[ -f "$DIR/alpha_pos_core/pyproject.toml" ] || { echo "!! core submodule missing — run: git submodule update --init"; exit 1; }

# --- 2. shared edge network (Caddy <-> app) -------------------------------
docker network inspect edge >/dev/null 2>&1 || docker network create edge

# --- 3. .env (secrets generated once, preserved across re-runs) ------------
rand()   { head -c "${1:-48}" /dev/urandom | base64 | tr -d '\n' | tr '+/' '-_' | tr -d '='; }
fernet() { head -c 32 /dev/urandom | base64 | tr '+/' '-_'; }
keep()   { [ -f "$DIR/.env" ] && sed -n "s/^$1=//p" "$DIR/.env" | head -n1 || true; }
SECRET="$(keep SECRET_KEY)";            SECRET="${SECRET:-$(rand 64)}"
DBPASS="$(keep DB_PASSWORD)";           DBPASS="${DBPASS:-$(rand 32)}"
FERNET="$(keep LICENSE_FERNET_KEY)";    FERNET="${FERNET:-$(fernet)}"
BTOK="$(keep DESKTOP_BRANCH_TOKEN)";    BTOK="${BTOK:-$(rand 32)}"
cat > "$DIR/.env" <<EOF
# Generated by deploy.sh — Alpha POS server edition
DEBUG=False
SECRET_KEY=${SECRET}
ALLOWED_HOSTS=${HOST},${IP},localhost,127.0.0.1
CSRF_TRUSTED_ORIGINS=https://${HOST}
CORS_ALLOW_ALL=True
DB_ENGINE=django.db.backends.postgresql
DB_NAME=alpha_pos
DB_USER=alpha_pos
DB_PASSWORD=${DBPASS}
DB_HOST=db
DB_PORT=5432
WEB_PORT=127.0.0.1:8000
REDIS_URL=redis://redis:6379/0
USE_REDIS=True
DEPLOYMENT_MODE=cloud
BRANCH_ID=cloud
LICENSE_FERNET_KEY=${FERNET}
LICENSE_CONTROL_CENTER_URL=${CONTROL_URL}
LICENSE_HEARTBEAT_DISABLED=1
DESKTOP_BRANCH_TOKEN=${BTOK}
BRANCH_TOKEN_MAP={"${BTOK}":"branch1"}
TRUST_FORWARDED_PROTO=True
EOF
echo ">> wrote .env (secrets preserved)"

# --- 4. edge overlay: join the app to the shared network as 'alpha-web' ----
cat > "$DIR/docker-compose.edge.yml" <<'EOF'
services:
  web:
    networks:
      default: {}
      edge:
        aliases: [alpha-web]
networks:
  edge:
    external: true
EOF

# --- 5. Caddy (automatic HTTPS; reverse_proxy upgrades WebSockets for free) -
mkdir -p "$DIR/caddy"
cat > "$DIR/caddy/Caddyfile" <<EOF
${HOST} {
	reverse_proxy alpha-web:8000
}
EOF
cat > "$DIR/caddy/docker-compose.yml" <<'EOF'
services:
  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    ports: ["80:80", "443:443"]
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    networks: [edge]
volumes:
  caddy_data:
  caddy_config:
networks:
  edge:
    external: true
EOF

# --- 6. build + start ------------------------------------------------------
SHA="$(git -C "$DIR" rev-parse --short=12 HEAD 2>/dev/null || echo unknown)"
( cd "$DIR" && GIT_SHA="$SHA" docker compose -f docker-compose.yaml -f docker-compose.edge.yml up -d --build )
( cd "$DIR/caddy" && docker compose up -d \
    && ( docker compose exec -T caddy caddy reload --config /etc/caddy/Caddyfile 2>/dev/null \
         || docker compose restart caddy ) )

# --- 7. license + admin (idempotent) --------------------------------------
DC="cd \"$DIR\" && docker compose -f docker-compose.yaml -f docker-compose.edge.yml exec -T web python manage.py"
eval "$DC activate_offline --email vendor@local --org 'AlphaPOS Cloud' --perpetual" || true
eval "$DC bootstrap_admin --email admin@alpha.local --password 'CHANGE-ME-strong'" || true

echo ""
echo "============================================================"
echo "  Alpha POS server is up:  https://${HOST}"
echo "  Admin: admin@alpha.local / CHANGE-ME-strong  (CHANGE IT)"
echo "  Desktop tills use this as CLOUD_SYNC_TOKEN:  ${BTOK}"
echo "============================================================"
