#!/usr/bin/env bash
#
# One-shot deploy for the Alpha POS SERVER edition (cloud back-office).
#
#   ./deploy.sh <SERVER_PUBLIC_IP>
#
# Idempotent — re-run to update (pulls code + the core submodule, rebuilds, keeps
# secrets + certs). Assumes Linux + Docker. Serves behind Caddy with automatic
# HTTPS via nip.io (no domain needed). The core spine is a git submodule, so the
# FIRST checkout must be `git clone --recurse-submodules` (this script also runs
# `submodule update --init` defensively).
set -euo pipefail
umask 077

IP="${1:?Usage: ./deploy.sh <SERVER_PUBLIC_IP>}"
DIR="$(cd "$(dirname "$0")" && pwd)"
HOST="pos.${IP}.nip.io"
CONTROL_URL="${LICENSE_CONTROL_CENTER_URL:-https://control.${IP}.nip.io}"

echo ">> Alpha POS server  ->  https://${HOST}"

# --- 1. latest code + core submodule --------------------------------------
DEPLOY_HEAD_BEFORE="$(git -C "$DIR" rev-parse HEAD 2>/dev/null || true)"
git -C "$DIR" pull --ff-only 2>/dev/null || echo "   (not a fast-forwardable checkout — skipping pull)"
DEPLOY_HEAD_AFTER="$(git -C "$DIR" rev-parse HEAD 2>/dev/null || true)"
if [ "${ALPHAPOS_DEPLOY_REEXEC:-0}" != "1" ] \
    && [ -n "$DEPLOY_HEAD_BEFORE" ] \
    && [ "$DEPLOY_HEAD_BEFORE" != "$DEPLOY_HEAD_AFTER" ]; then
    echo ">> checkout advanced; restarting with the updated deploy script"
    exec env ALPHAPOS_DEPLOY_REEXEC=1 bash "$DIR/deploy.sh" "$IP"
fi
git -C "$DIR" submodule update --init --recursive
[ -f "$DIR/alpha_pos_core/pyproject.toml" ] || { echo "!! core submodule missing — run: git submodule update --init"; exit 1; }

# --- 2. shared edge network (Caddy <-> app) -------------------------------
docker network inspect edge >/dev/null 2>&1 || docker network create edge

# --- 3. .env (secrets generated once, preserved across re-runs) ------------
rand()   { head -c "${1:-48}" /dev/urandom | base64 | tr -d '\n' | tr '+/' '-_' | tr -d '='; }
fernet() { head -c 32 /dev/urandom | base64 | tr '+/' '-_'; }
keep()   { [ -f "$DIR/.env" ] && sed -n "s/^$1=//p" "$DIR/.env" | head -n1 || true; }
SECRET="$(keep SECRET_KEY)";            SECRET="${SECRET:-$(rand 64)}"
DBPASS="$(keep DB_PASSWORD)";           DBPASS="${DBPASS:-$(rand 32)}"
FERNET="$(keep LICENSE_FERNET_KEY)";    FERNET="${FERNET:-$(fernet)}"
BTOK="$(keep DESKTOP_BRANCH_TOKEN)";    BTOK="${BTOK:-$(rand 32)}"
# Smart Food customer bot (Telegram Mini App). Configure its token once in the
# server-side .env; deploys preserve it. Never bake a live bot credential into
# source. Set YANDEX_GEOCODER_KEY there for server-side address geocoding.
CBOT="$(keep CUSTOMER_BOT_TOKEN)"
CWHSEC="$(keep CUSTOMER_WEBHOOK_SECRET)"; CWHSEC="${CWHSEC:-$(rand 32)}"
YGEO="$(keep YANDEX_GEOCODER_KEY)"
# Bootstrap credentials are generated once and kept only in the server-side
# .env. Never bake a real credential or a shared default password into Git.
ADMIN_EMAIL="$(keep ALPHA_POS_ADMIN_EMAIL)"; ADMIN_EMAIL="${ADMIN_EMAIL:-admin@alpha.local}"
ADMIN_PASS="$(keep ALPHA_POS_ADMIN_PASSWORD)"; ADMIN_PASS="${ADMIN_PASS:-$(rand 32)}"
# Auto bot-dispatch + auto courier-assign default OFF for a safe rollout: presence
# needs tills on 1.0.13+ (older tills send no device presence, so auto-dispatch
# would reject every bot order). Flip to true in .env once the tills are updated.
SAD="$(keep SMARTFOOD_AUTO_DISPATCH)";   SAD="${SAD:-false}"
CAA="$(keep COURIER_AUTO_ASSIGN)";       CAA="${CAA:-false}"
# AI assistant. Keys are preserved across redeploys via keep() — set each once in
# .env (never committed to git). Provider + model are safe to bake. OpenAI is the
# active provider; Claude + Gemini config are kept as fallbacks.
GAPI="$(keep GEMINI_API_KEY)"
AAPI="$(keep ANTHROPIC_API_KEY)"
AMODEL="$(keep ANTHROPIC_MODEL)"; AMODEL="${AMODEL:-claude-sonnet-4-5}"
OAPI="$(keep OPENAI_API_KEY)"
OMODEL="$(keep OPENAI_MODEL)"; OMODEL="${OMODEL:-gpt-5.5}"
cat > "$DIR/.env" <<EOF
# Generated by deploy.sh — Alpha POS server edition
DEBUG=False
SECRET_KEY=${SECRET}
ALLOWED_HOSTS=${HOST},${IP},localhost,127.0.0.1
CSRF_TRUSTED_ORIGINS=https://${HOST}
CORS_ALLOW_ALL=True
DB_ENGINE=django.db.backends.postgresql
DB_NAME=alpha_pos
DB_USER=alpha_pos
DB_PASSWORD=${DBPASS}
DB_HOST=db
DB_PORT=5432
WEB_PORT=127.0.0.1:8000
# Make a later bare "docker compose up" retain the Caddy edge attachment.
# Without this, Compose recreates the web service from only docker-compose.yaml and the
# healthy app becomes publicly unreachable with a 502 until the overlay is
# supplied again.
COMPOSE_FILE=docker-compose.yaml:docker-compose.edge.yml
REDIS_URL=redis://redis:6379/0
USE_REDIS=True
DEPLOYMENT_MODE=cloud
BRANCH_ID=cloud
LICENSE_FERNET_KEY=${FERNET}
LICENSE_CONTROL_CENTER_URL=${CONTROL_URL}
LICENSE_HEARTBEAT_DISABLED=1
ALPHA_POS_ADMIN_EMAIL=${ADMIN_EMAIL}
ALPHA_POS_ADMIN_PASSWORD=${ADMIN_PASS}
DESKTOP_BRANCH_TOKEN=${BTOK}
BRANCH_TOKEN_MAP={"${BTOK}":"branch1"}
TRUST_FORWARDED_PROTO=True
# --- Smart Food customer Telegram bot (Mini App delivery) ---
CUSTOMER_BOT_TOKEN=${CBOT}
CUSTOMER_WEBAPP_URL=${CUSTOMER_WEBAPP_URL:-https://${HOST}/webapp/}
CUSTOMER_WEBHOOK_SECRET=${CWHSEC}
SMARTFOOD_AUTH_TTL=86400
SMARTFOOD_AUTO_DISPATCH=${SAD}
COURIER_AUTO_ASSIGN=${CAA}
YANDEX_GEOCODER_KEY=${YGEO}
# --- AI assistant (LLM) — server-side only ---
# OpenAI is active (gpt-5.4-mini) with persisted chat history. Claude + Gemini
# config are kept as fallbacks — flip AI_PROVIDER to switch.
AI_PROVIDER=openai
OPENAI_API_KEY=${OAPI}
OPENAI_MODEL=${OMODEL}
ANTHROPIC_API_KEY=${AAPI}
ANTHROPIC_MODEL=${AMODEL}
GEMINI_MODEL=gemini-2.5-flash
GEMINI_API_KEY=${GAPI}
EOF
chmod 600 "$DIR/.env"
echo ">> wrote .env (secrets preserved)"

# --- 4. edge overlay: join the app to the shared network as 'alpha-web' ----
cat > "$DIR/docker-compose.edge.yml" <<'EOF'
services:
  web:
    networks:
      default: {}
      edge:
        aliases: [alpha-web]
networks:
  edge:
    external: true
EOF

# --- 5. Caddy (automatic HTTPS; reverse_proxy upgrades WebSockets for free) -
mkdir -p "$DIR/caddy"
cat > "$DIR/caddy/Caddyfile" <<EOF
${HOST} {
	reverse_proxy alpha-web:8000
}
EOF
cat > "$DIR/caddy/docker-compose.yml" <<'EOF'
services:
  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    ports: ["80:80", "443:443"]
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    networks: [edge]
volumes:
  caddy_data:
  caddy_config:
networks:
  edge:
    external: true
EOF

# --- 6. build + start ------------------------------------------------------
SHA="$(git -C "$DIR" rev-parse --short=12 HEAD 2>/dev/null || echo unknown)"
( cd "$DIR" && GIT_SHA="$SHA" docker compose -f docker-compose.yaml -f docker-compose.edge.yml up -d --build )
( cd "$DIR/caddy" && docker compose up -d \
    && ( docker compose exec -T caddy caddy reload --config /etc/caddy/Caddyfile 2>/dev/null \
         || docker compose restart caddy ) )

# --- 7. license + admin (idempotent) --------------------------------------
DC="cd \"$DIR\" && docker compose -f docker-compose.yaml -f docker-compose.edge.yml exec -T web python manage.py"
# Wait for the web container's entrypoint to FINISH migrations before provisioning.
# `up -d` returns when the container starts, not when migrate completes; uvicorn
# only starts after migrate, so a passing /healthz means the schema is ready.
# Without this, activate_offline raced a half-migrated DB -> "relation
# licensing_license does not exist".
echo ">> waiting for web (migrations + uvicorn) ..."
for _i in $(seq 1 90); do
    ( cd "$DIR" && docker compose -f docker-compose.yaml -f docker-compose.edge.yml exec -T web curl -fsS http://127.0.0.1:8000/healthz >/dev/null 2>&1 ) \
        && { echo ">> web ready"; break; }
    sleep 2
done
bash "$DIR/deploy/verify_public_route.sh" "$DIR" "$HOST" "$SHA"
eval "$DC migrate --noinput" || true   # idempotent safety-net in case the wait timed out
eval "$DC activate_offline --email vendor@local --org 'AlphaPOS Cloud' --perpetual" || true
eval "$DC bootstrap_admin" || true

echo ""
echo "============================================================"
echo "  Alpha POS server is up:  https://${HOST}"
echo "  POS API admin credentials are stored in the root-only .env file."
echo "  No predictable Django /admin/ accounts are created automatically."
echo "  Desktop branch token is stored in the root-only .env file."
echo "============================================================"
