# Generated by Django 5.2.13 on 2026-04-23 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_leavetype_employeecontract_contractdocument_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='medical_book_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='medical_book_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='status_tags',
            field=models.JSONField(blank=True, default=list, help_text='Tags: BLACKLIST, POSITIVE, NEGATIVE, WARNING, VIP'),
        ),
    ]
