# Generated by Django 6.0.3 on 2026-05-23 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_secure_document_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELED', 'Canceled')], default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='performancegoal',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELED', 'Canceled')], default='PENDING', max_length=12),
        ),
    ]
