# Generated by Django 6.0.3 on 2026-09-18 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_profitability'),
        ('base', '0067_waiter_policy_audit'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=512, unique=True)),
                ('platform', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android')], max_length=10)),
                ('app_version', models.CharField(blank=True, default='', max_length=32)),
                ('locale', models.CharField(default='uz', max_length=8)),
                ('prefs', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_devices', to='base.session')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_devices', to='base.user')),
            ],
        ),
        migrations.CreateModel(
            name='OwnerPushOutbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_key', models.CharField(max_length=80)),
                ('kind', models.CharField(max_length=32)),
                ('title', models.CharField(max_length=120)),
                ('body', models.CharField(max_length=400)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('DEAD', 'Gave up')], default='PENDING', max_length=10)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField()),
                ('last_error', models.CharField(blank=True, default='', max_length=300)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbox', to='admins.admindevice')),
            ],
        ),
        migrations.AddIndex(
            model_name='admindevice',
            index=models.Index(fields=['user', 'is_active'], name='admins_admi_user_id_d831d1_idx'),
        ),
        migrations.AddIndex(
            model_name='ownerpushoutbox',
            index=models.Index(fields=['status', 'next_attempt_at'], name='admins_owne_status_90d627_idx'),
        ),
        migrations.AddConstraint(
            model_name='ownerpushoutbox',
            constraint=models.UniqueConstraint(fields=('device', 'event_key'), name='uniq_owner_push_device_event'),
        ),
    ]
