#!/usr/bin/env bash
#
# One-shot server deploy for Alpha POS (+ the POS Control Center when present),
# behind a Caddy reverse proxy with automatic HTTPS via nip.io (no domain).
#
#   ./deploy.sh <SERVER_PUBLIC_IP>
#
# Staged rollout supported: if the control-center repo isn't cloned yet, this
# deploys ONLY alpha_pos + Caddy. Clone pos_control next to alpha_pos and
# re-run to add the control center (secrets + certs are preserved).
#
# Assumes Linux + Docker, and that this script lives at ~/alpha_pos/deploy/.
# Control center is expected at ~/pos_control (override: CONTROL_DIR=/path).
set -euo pipefail

IP="${1:?Usage: ./deploy.sh <SERVER_PUBLIC_IP>}"
ALPHA_DIR="${ALPHA_DIR:-$(cd "$(dirname "$0")/.." && pwd)}"
CONTROL_DIR="${CONTROL_DIR:-$(dirname "$ALPHA_DIR")/pos_control}"
DEPLOY_DIR="$ALPHA_DIR/deploy"

POS_HOST="pos.${IP}.nip.io"
CONTROL_HOST="control.${IP}.nip.io"

HAVE_CONTROL=false
[ -d "$CONTROL_DIR" ] && HAVE_CONTROL=true

echo ">> alpha_pos : $ALPHA_DIR"
echo ">> POS URL   : https://${POS_HOST}"
if $HAVE_CONTROL; then
    echo ">> control   : $CONTROL_DIR"
    echo ">> CTRL URL  : https://${CONTROL_HOST}"
else
    echo ">> control center not cloned yet -> deploying alpha_pos ONLY"
    echo "   (clone pos_control next to alpha_pos and re-run to add it)"
fi

# --- helpers ---------------------------------------------------------------
rand()   { head -c "${1:-48}" /dev/urandom | base64 | tr -d '\n' | tr '+/' '-_' | tr -d '='; }
fernet() { head -c 32 /dev/urandom | base64 | tr '+/' '-_'; }  # 32-byte urlsafe b64 = Fernet key
keep()   { local f="$1" k="$2"; [ -f "$f" ] && sed -n "s/^${k}=//p" "$f" | head -n1 || true; }

# --- 0. core submodule ------------------------------------------------------
# The shared spine (alpha_pos_core) is a git submodule the Dockerfile installs via
# `pip install ./alpha_pos_core`. A clone done without --recurse-submodules leaves
# that dir empty and the image build fails. Pull it defensively so the deploy works
# regardless of how the repo was cloned.
if [ -f "$ALPHA_DIR/.gitmodules" ]; then
    git -C "$ALPHA_DIR" submodule update --init --recursive
fi
[ -f "$ALPHA_DIR/alpha_pos_core/pyproject.toml" ] || {
    echo "!! core submodule missing at $ALPHA_DIR/alpha_pos_core"
    echo "   run: git -C $ALPHA_DIR submodule update --init --recursive"; exit 1; }
echo ">> core submodule present"

# --- 1. shared edge network ------------------------------------------------
docker network inspect edge >/dev/null 2>&1 || docker network create edge
echo ">> edge network ready"

# --- 2. alpha_pos .env -----------------------------------------------------
A_ENV="$ALPHA_DIR/.env"
A_SECRET="$(keep "$A_ENV" SECRET_KEY)";   A_SECRET="${A_SECRET:-$(rand 64)}"
A_DBPASS="$(keep "$A_ENV" DB_PASSWORD)";  A_DBPASS="${A_DBPASS:-$(rand 32)}"
A_FERNET="$(keep "$A_ENV" LICENSE_FERNET_KEY)"; A_FERNET="${A_FERNET:-$(fernet)}"
A_SYNCMGMT="$(keep "$A_ENV" SYNC_MANAGEMENT_TOKEN)"; A_SYNCMGMT="${A_SYNCMGMT:-$(rand 32)}"
A_CLOUDTOK="$(keep "$A_ENV" CLOUD_SYNC_TOKEN)"; A_CLOUDTOK="${A_CLOUDTOK:-$(rand 32)}"
# Per-branch token the desktops authenticate with (Authorization: Branch <tok>),
# bound to a branch id via BRANCH_TOKEN_MAP so X-Branch-ID can't be spoofed.
A_BRANCHTOK="$(keep "$A_ENV" DESKTOP_BRANCH_TOKEN)"; A_BRANCHTOK="${A_BRANCHTOK:-$(rand 32)}"
A_BRANCHID="branch1"
# AI — operator picks the provider + pastes the matching key once; preserved.
A_AIPROVIDER="$(keep "$A_ENV" AI_PROVIDER)"; A_AIPROVIDER="${A_AIPROVIDER:-claude}"
A_AIKEY="$(keep "$A_ENV" ANTHROPIC_API_KEY)"
A_AIMODEL="$(keep "$A_ENV" ANTHROPIC_MODEL)"; A_AIMODEL="${A_AIMODEL:-claude-sonnet-4-6}"
A_GEMKEY="$(keep "$A_ENV" GEMINI_API_KEY)"
A_GEMMODEL="$(keep "$A_ENV" GEMINI_MODEL)"; A_GEMMODEL="${A_GEMMODEL:-gemini-2.5-flash}"
cat > "$A_ENV" <<EOF
# Generated by deploy/deploy.sh — Alpha POS cloud backend
DEBUG=False
SECRET_KEY=${A_SECRET}
ALLOWED_HOSTS=${POS_HOST},${IP},localhost,127.0.0.1
CSRF_TRUSTED_ORIGINS=https://${POS_HOST}
# CORS open to every origin (any frontend domain can call the API). CSRF and
# secure cookies stay enforced — clients use bearer tokens, so credentialed
# CORS is off (the browser-safe allow-all combination).
CORS_ALLOW_ALL=True
WEB_PORT=127.0.0.1:8001
# This is the central hub (not a branch): timestamp records it originates so
# they distribute to branches via /changes, and don't try to push to itself.
DEPLOYMENT_MODE=cloud
# The hub needs its OWN branch id, distinct from every branch (branch1, ...),
# or /changes would treat hub-created records as the branch's own and skip them
# on pull.
BRANCH_ID=cloud

DB_ENGINE=django.db.backends.postgresql
DB_NAME=alpha_pos
DB_USER=alpha_pos
DB_PASSWORD=${A_DBPASS}
DB_HOST=db
DB_PORT=5432

USE_REDIS=True
REDIS_URL=redis://redis:6379/0

# Behind Caddy (TLS terminated at the proxy)
TRUST_FORWARDED_PROTO=True
TRUST_FORWARDED_FOR=True

# Licensing: vendor infra, licensed offline (no control-center call, which also
# avoids the https-required check). Heartbeat daemon off.
LICENSE_FERNET_KEY=${A_FERNET}
LICENSE_HEARTBEAT_DISABLED=1

# Sync: this server RECEIVES branch data.
SYNC_ENABLED=True
SYNC_MANAGEMENT_TOKEN=${A_SYNCMGMT}
CLOUD_SYNC_TOKEN=${A_CLOUDTOK}
DESKTOP_BRANCH_TOKEN=${A_BRANCHTOK}
BRANCH_TOKEN_MAP={"${A_BRANCHTOK}":"${A_BRANCHID}"}
ALLOWED_BRANCH_IDS=${A_BRANCHID}

# AI assistant + demand forecast. AI_PROVIDER picks claude|gemini; fill the
# matching key. Empty key => AI endpoints return a clean "key missing".
AI_PROVIDER=${A_AIPROVIDER}
ANTHROPIC_API_KEY=${A_AIKEY}
ANTHROPIC_MODEL=${A_AIMODEL}
GEMINI_API_KEY=${A_GEMKEY}
GEMINI_MODEL=${A_GEMMODEL}
EOF
echo ">> wrote $A_ENV"

# alpha_pos edge override (join the proxy network with a stable alias)
cat > "$ALPHA_DIR/docker-compose.edge.yml" <<'EOF'
services:
  web:
    networks:
      default: {}
      edge:
        aliases: [alpha-web]
networks:
  edge:
    external: true
EOF

# --- 3. pos_control .env + override (only if cloned) -----------------------
if $HAVE_CONTROL; then
    C_ENV="$CONTROL_DIR/.env"
    C_SECRET="$(keep "$C_ENV" SECRET_KEY)";  C_SECRET="${C_SECRET:-$(rand 64)}"
    C_DBPASS="$(keep "$C_ENV" DB_PASSWORD)"; C_DBPASS="${C_DBPASS:-$(rand 32)}"
    cat > "$C_ENV" <<EOF
# Generated by deploy/deploy.sh — POS Control Center
DEBUG=False
SECRET_KEY=${C_SECRET}
ALLOWED_HOSTS=${CONTROL_HOST},${IP},localhost,127.0.0.1
CSRF_TRUSTED_ORIGINS=https://${CONTROL_HOST}
WEB_PORT=127.0.0.1:8002

DB_ENGINE=django.db.backends.postgresql
DB_NAME=pos_control_center
DB_USER=pos_control_center
DB_PASSWORD=${C_DBPASS}
DB_HOST=db
DB_PORT=5432

TRUST_FORWARDED_PROTO=True
EOF
    echo ">> wrote $C_ENV"
    cat > "$CONTROL_DIR/docker-compose.edge.yml" <<'EOF'
services:
  web:
    networks:
      default: {}
      edge:
        aliases: [control-web]
networks:
  edge:
    external: true
EOF
fi

# --- 4. Caddy config (sites for whatever is being deployed) ----------------
mkdir -p "$DEPLOY_DIR/caddy"
{
    echo "${POS_HOST} {"
    echo "	reverse_proxy alpha-web:8000"
    echo "}"
    if $HAVE_CONTROL; then
        echo ""
        echo "${CONTROL_HOST} {"
        echo "	reverse_proxy control-web:8000"
        echo "}"
    fi
} > "$DEPLOY_DIR/caddy/Caddyfile"
echo ">> wrote Caddyfile"

# --- 5. bring the stacks up ------------------------------------------------
echo ">> building + starting alpha_pos ..."
A_SHA="$(git -C "$ALPHA_DIR" rev-parse --short=12 HEAD 2>/dev/null || echo unknown)"
( cd "$ALPHA_DIR" && GIT_SHA="$A_SHA" docker compose -f docker-compose.yaml -f docker-compose.edge.yml up -d --build )

if $HAVE_CONTROL; then
    echo ">> building + starting pos_control ..."
    ( cd "$CONTROL_DIR" && docker compose -f docker-compose.yaml -f docker-compose.edge.yml up -d --build )
fi

echo ">> starting/reloading caddy ..."
( cd "$DEPLOY_DIR/caddy" && docker compose up -d \
    && ( docker compose exec -T caddy caddy reload --config /etc/caddy/Caddyfile 2>/dev/null \
         || docker compose restart caddy ) )

# --- 6. next steps ---------------------------------------------------------
A="cd \"$ALPHA_DIR\" && docker compose -f docker-compose.yaml -f docker-compose.edge.yml"
cat <<EOF

============================================================
  Stacks are up. Finish with these one-time steps:
============================================================

# 1) Alpha POS cloud — license offline (clears the kill switch) + make admin:
$A exec -T web python manage.py activate_offline --email vendor@local --org "AlphaPOS Cloud" --perpetual
$A exec -T web python manage.py bootstrap_admin --email admin@alpha.local --password 'CHANGE-ME-strong'

# 2) Verify (give Caddy ~30s on first run to issue the certificate):
curl -fsS https://${POS_HOST}/healthz && echo "  POS OK"

Cloud POS admin : https://${POS_HOST}/admin/  (login admin@alpha.local)

# Desktop sync config — paste into the desktop Configuration tab:
#   CLOUD_SYNC_URL   = https://${POS_HOST}/api/sync
#   CLOUD_SYNC_TOKEN = ${A_BRANCHTOK}
#   BRANCH_ID        = ${A_BRANCHID}
#   SYNC_ENABLED     = True
EOF
if $HAVE_CONTROL; then
cat <<EOF

# 3) Control center — create the dashboard superuser (interactive):
cd "$CONTROL_DIR" && docker compose -f docker-compose.yaml -f docker-compose.edge.yml exec web python manage.py createsuperuser
Control center  : https://${CONTROL_HOST}/
EOF
else
cat <<EOF

# (Control center not deployed yet.) To add it later:
#   cd ~ && git clone https://github.com/MythicalCosmic/pos_control.git
#   cd ~/alpha_pos/deploy && ./deploy.sh ${IP}
EOF
fi
echo "============================================================"
