# Generated by Django 6.0.3 on 2026-06-16 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_customer_alter_rolepermission_role_alter_user_role_and_more'),
        ('smartfood', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_uz', models.CharField(blank=True, default='', max_length=120)),
                ('name_ru', models.CharField(blank=True, default='', max_length=120)),
                ('name_en', models.CharField(blank=True, default='', max_length=120)),
                ('desc_uz', models.TextField(blank=True, default='')),
                ('desc_ru', models.TextField(blank=True, default='')),
                ('desc_en', models.TextField(blank=True, default='')),
                ('kind', models.CharField(choices=[('FREE_PRODUCT', 'Free product'), ('DISCOUNT', 'Discount (UZS off)'), ('FREE_DELIVERY', 'Free delivery'), ('CUSTOM', 'Custom prize')], default='CUSTOM', max_length=16)),
                ('points_cost', models.PositiveIntegerField(default=0)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('image_url', models.URLField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('stock', models.IntegerField(blank=True, help_text='Remaining stock; blank = unlimited.', null=True)),
                ('per_customer_limit', models.PositiveIntegerField(default=0, help_text='Max redemptions per customer; 0 = unlimited.')),
                ('sort_order', models.IntegerField(default=0)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='base.product')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Redemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('points_spent', models.PositiveIntegerField(default=0)),
                ('reward_name', models.CharField(blank=True, default='', max_length=120)),
                ('kind', models.CharField(blank=True, default='', max_length=16)),
                ('status', models.CharField(choices=[('ISSUED', 'Issued'), ('FULFILLED', 'Fulfilled'), ('CANCELED', 'Canceled')], db_index=True, default='ISSUED', max_length=12)),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='smartfood.customer')),
                ('fulfilled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='base.user')),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='smartfood.reward')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='LoyaltyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('EARN_ORDER', 'Earned (order)'), ('EARN_SCAN', 'Earned (in-store)'), ('SPEND_ORDER', 'Spent (order)'), ('REDEEM', 'Redeemed (gift)'), ('GRANT', 'Granted (bonus/gift)'), ('REFUND', 'Refunded'), ('ADJUST', 'Adjustment')], max_length=16)),
                ('points', models.IntegerField(default=0)),
                ('balance_after', models.IntegerField(default=0)),
                ('reason', models.CharField(blank=True, default='', max_length=200)),
                ('bot_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='smartfood.botorder')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_txns', to='smartfood.customer')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='base.user')),
                ('redemption', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='txns', to='smartfood.redemption')),
                ('reward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='smartfood.reward')),
            ],
            options={
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['customer', '-id'], name='smartfood_l_custome_aa19e7_idx')],
            },
        ),
    ]
