# Generated by Django 6.0.3 on 2026-08-19 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0056_remove_exclusive_shift_device_slot'),
        ('smartfood', '0005_botvisit_botconfig_bot_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title_uz', models.CharField(blank=True, default='', max_length=140)),
                ('title_ru', models.CharField(blank=True, default='', max_length=140)),
                ('title_en', models.CharField(blank=True, default='', max_length=140)),
                ('subtitle_uz', models.CharField(blank=True, default='', max_length=240)),
                ('subtitle_ru', models.CharField(blank=True, default='', max_length=240)),
                ('subtitle_en', models.CharField(blank=True, default='', max_length=240)),
                ('image_url', models.URLField(blank=True, default='')),
                ('action_type', models.CharField(choices=[('NONE', 'No action'), ('CATALOG', 'Open catalog'), ('PRODUCT', 'Open product'), ('LOYALTY', 'Open rewards')], default='NONE', max_length=12)),
                ('is_active', models.BooleanField(db_index=True, default=False)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='base.product')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'indexes': [models.Index(fields=['is_active', 'sort_order'], name='smartfood_b_is_acti_f2d2c2_idx')],
            },
        ),
    ]
