# Generated by Django 6.0.3 on 2026-08-20 18:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def backfill_order_locations(apps, schema_editor):
    BotOrder = apps.get_model('smartfood', 'BotOrder')
    alias = schema_editor.connection.alias
    pending = []
    queryset = (
        BotOrder.objects.using(alias)
        .select_related('address')
        .filter(address__isnull=False)
        .filter(models.Q(address_lat__isnull=True) | models.Q(address_lng__isnull=True))
    )
    for order in queryset.iterator(chunk_size=1000):
        address = order.address
        if order.address_lat is None:
            order.address_lat = address.lat
        if order.address_lng is None:
            order.address_lng = address.lng
        pending.append(order)
        if len(pending) == 1000:
            BotOrder.objects.using(alias).bulk_update(
                pending, ['address_lat', 'address_lng'], batch_size=1000,
            )
            pending = []
    if pending:
        BotOrder.objects.using(alias).bulk_update(
            pending, ['address_lat', 'address_lng'], batch_size=1000,
        )


def canonicalize_customer_phones(apps, schema_editor):
    """Converge valid legacy spellings before profile readiness is queried."""
    Customer = apps.get_model('smartfood', 'Customer')
    alias = schema_editor.connection.alias
    pending = []
    for customer in Customer.objects.using(alias).all().iterator(chunk_size=1000):
        raw = str(customer.phone_number or '')
        digits = ''.join(character for character in raw if '0' <= character <= '9')
        if digits.startswith('00'):
            digits = digits[2:]
        if len(digits) == 9:
            digits = '998' + digits
        elif len(digits) == 10 and digits.startswith('0'):
            digits = '998' + digits[1:]
        if len(digits) != 12 or not digits.startswith('998') or raw == digits:
            continue
        customer.phone_number = digits
        pending.append(customer)
        if len(pending) == 1000:
            Customer.objects.using(alias).bulk_update(
                pending, ['phone_number'], batch_size=1000,
            )
            pending = []
    if pending:
        Customer.objects.using(alias).bulk_update(
            pending, ['phone_number'], batch_size=1000,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0056_remove_exclusive_shift_device_slot'),
        ('smartfood', '0006_botbanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='language_overridden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='broadcast_opted_in',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='telegram_reachable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='profile_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(
            canonicalize_customer_phones,
            migrations.RunPython.noop,
        ),
        migrations.AddField(
            model_name='botorder',
            name='address_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='botorder',
            name='address_lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.RunPython(
            backfill_order_locations,
            migrations.RunPython.noop,
        ),
        migrations.CreateModel(
            name='BotBroadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
                ('text_uz', models.TextField(blank=True, default='')),
                ('text_ru', models.TextField(blank=True, default='')),
                ('text_en', models.TextField(blank=True, default='')),
                ('image_url', models.URLField(blank=True, default='')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('QUEUED', 'Queued'), ('SENDING', 'Sending'), ('SENT', 'Sent'), ('PARTIAL', 'Partially sent'), ('FAILED', 'Failed')], db_index=True, default='DRAFT', max_length=12)),
                ('recipient_count', models.PositiveIntegerField(default=0)),
                ('delivered_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('queued_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='base.user')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='base.user')),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='BotOutboundMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('ORDER_STATUS', 'Order status'), ('BROADCAST', 'Broadcast')], db_index=True, max_length=16)),
                ('event_key', models.CharField(blank=True, default='', max_length=32)),
                ('chat_id', models.BigIntegerField()),
                ('language', models.CharField(choices=[('uz', 'Uzbek'), ('ru', 'Russian'), ('en', 'English')], default='uz', max_length=2)),
                ('text', models.TextField()),
                ('image_url', models.URLField(blank=True, default='')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped')], db_index=True, default='PENDING', max_length=12)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('claim_token', models.UUIDField(blank=True, editable=False, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('telegram_message_id', models.BigIntegerField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, default='', max_length=500)),
                ('bot_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbound_messages', to='smartfood.botorder')),
                ('broadcast', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='smartfood.botbroadcast')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outbound_messages', to='smartfood.customer')),
            ],
            options={
                'ordering': ['next_attempt_at', 'id'],
                'indexes': [models.Index(fields=['status', 'next_attempt_at'], name='sf_outbound_status_next_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('bot_order__isnull', False)), fields=('bot_order', 'event_key'), name='sf_outbound_order_event_uniq'), models.UniqueConstraint(condition=models.Q(('broadcast__isnull', False)), fields=('broadcast', 'customer'), name='sf_outbound_broadcast_customer_uniq')],
            },
        ),
    ]
