# Generated by Django 6.0.3 on 2026-09-12 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0065_direct_supplier_invoices'),
        ('smartfood', '0007_customer_language_overridden_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='botconfig',
            name='loyalty_earning_basis',
            field=models.CharField(choices=[('PAID_MERCHANDISE', 'Merchandise after point discounts'), ('MERCHANDISE_SUBTOTAL', 'Merchandise before point discounts')], default='PAID_MERCHANDISE', max_length=24),
        ),
        migrations.AddField(
            model_name='botconfig',
            name='reward_valid_days',
            field=models.PositiveSmallIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='botorder',
            name='loyalty_policy_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='loyaltytransaction',
            name='pos_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='base.order'),
        ),
        migrations.AddField(
            model_name='redemption',
            name='action_history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='redemption',
            name='canceled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='redemption',
            name='canceled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='base.user'),
        ),
        migrations.AddField(
            model_name='redemption',
            name='cancellation_reason',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='redemption',
            name='expires_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='redemption',
            name='reward_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='redemption',
            name='stock_reserved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='redemption',
            name='status',
            field=models.CharField(choices=[('ISSUED', 'Issued'), ('FULFILLED', 'Fulfilled'), ('CANCELED', 'Canceled'), ('EXPIRED', 'Expired (points returned)')], db_index=True, default='ISSUED', max_length=12),
        ),
        migrations.AddConstraint(
            model_name='loyaltytransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('kind__in', ['EARN_SCAN', 'REVERSE_SCAN']), ('pos_order__isnull', False)), fields=('pos_order', 'kind'), name='sf_loyalty_scan_order_unique'),
        ),
    ]
