# Generated by Django 6.0.3 on 2026-09-12 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartfood', '0008_loyalty_accounting_and_policy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loyaltytransaction',
            name='kind',
            field=models.CharField(choices=[('EARN_ORDER', 'Earned (order)'), ('EARN_SCAN', 'Earned (in-store)'), ('REVERSE_SCAN', 'Reversed (in-store refund)'), ('SPEND_ORDER', 'Spent (order)'), ('REDEEM', 'Redeemed (gift)'), ('GRANT', 'Granted (bonus/gift)'), ('REFUND', 'Refunded'), ('ADJUST', 'Adjustment')], max_length=16),
        ),
    ]
