# Generated by Django 6.0.3 on 2026-09-12 13:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartfood', '0009_receipt_refund_reversal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botconfig',
            name='loyalty_earn_per',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='botconfig',
            name='loyalty_point_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='botconfig',
            name='reward_valid_days',
            field=models.PositiveSmallIntegerField(default=30, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3650)]),
        ),
    ]
