# Generated by Django 6.0.3 on 2026-06-16 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0030_order_chef_queue_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default='', max_length=50)),
                ('last_name', models.CharField(blank=True, default='', max_length=50)),
                ('phone', models.CharField(db_index=True, max_length=24)),
                ('vehicle', models.CharField(blank=True, default='Scooter', max_length=32)),
                ('plate', models.CharField(blank=True, default='', max_length=24)),
                ('code', models.CharField(max_length=16, unique=True)),
                ('branch_id', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('branch_name', models.CharField(blank=True, default='', max_length=120)),
                ('rating', models.DecimalField(decimal_places=1, default=5.0, max_digits=2)),
                ('online', models.BooleanField(default=False)),
                ('share_loc', models.BooleanField(default=True)),
                ('shift_started_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='courier', to='base.user')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='LocationPing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('at', models.DateTimeField(auto_now=True)),
                ('courier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='couriers.courier')),
            ],
        ),
        migrations.CreateModel(
            name='PushToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('platform', models.CharField(blank=True, default='', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_tokens', to='couriers.courier')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(choices=[('ASSIGNED', 'Assigned (kitchen preparing)'), ('READY', 'Ready for pickup'), ('PICKED_UP', 'Picked up'), ('ON_WAY', 'On the way'), ('DELIVERED', 'Delivered'), ('DECLINED', 'Declined / unassigned')], db_index=True, default='ASSIGNED', max_length=12)),
                ('fee', models.BigIntegerField(default=0)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('ready_at', models.DateTimeField(blank=True, null=True)),
                ('picked_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('declined_reason', models.CharField(blank=True, default='', max_length=200)),
                ('addr_text', models.CharField(blank=True, default='', max_length=255)),
                ('addr_landmark', models.CharField(blank=True, default='', max_length=255)),
                ('addr_lat', models.FloatField(blank=True, null=True)),
                ('addr_lng', models.FloatField(blank=True, null=True)),
                ('distance_km', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('courier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='couriers.courier')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='courier_delivery', to='base.order')),
            ],
            options={
                'ordering': ['-assigned_at'],
                'indexes': [models.Index(fields=['courier', 'step'], name='couriers_de_courier_6327f2_idx')],
            },
        ),
    ]
