# Generated by Django 6.0.3 on 2026-06-20 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_customer_alter_rolepermission_role_alter_user_role_and_more'),
        ('couriers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourierNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(blank=True, default='bell', max_length=24)),
                ('tone', models.CharField(blank=True, default='primary', max_length=12)),
                ('title', models.CharField(max_length=160)),
                ('body', models.CharField(blank=True, default='', max_length=400)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='couriers.courier')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='base.order')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['courier', 'read_at'], name='couriers_co_courier_6d0109_idx')],
            },
        ),
        migrations.CreateModel(
            name='CourierPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card (terminal)'), ('QR', 'QR / online')], max_length=8)),
                ('amount', models.BigIntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('REFUNDED', 'Refunded'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=10)),
                ('link', models.CharField(blank=True, default='', max_length=512)),
                ('external_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('branch_id', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('courier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='couriers.courier')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courier_payments', to='base.order')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['courier', 'status'], name='couriers_co_courier_4c0ecb_idx'), models.Index(fields=['order', 'status'], name='couriers_co_order_i_f71fd8_idx')],
            },
        ),
        migrations.CreateModel(
            name='CourierSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('period_start', models.DateTimeField(blank=True, null=True)),
                ('period_end', models.DateTimeField(db_index=True)),
                ('deliveries', models.IntegerField(default=0)),
                ('cash_collected', models.BigIntegerField(default=0)),
                ('qr_collected', models.BigIntegerField(default=0)),
                ('delivery_fees', models.BigIntegerField(default=0)),
                ('bonuses', models.BigIntegerField(default=0)),
                ('tips', models.BigIntegerField(default=0)),
                ('net_payout', models.BigIntegerField(default=0)),
                ('handover_code', models.CharField(blank=True, default='', max_length=24)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='couriers.courier')),
            ],
            options={
                'ordering': ['-at'],
                'indexes': [models.Index(fields=['courier', 'period_end'], name='couriers_co_courier_f3bff3_idx')],
            },
        ),
        migrations.CreateModel(
            name='LocationTrailPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trail', to='couriers.courier')),
            ],
            options={
                'ordering': ['at'],
                'indexes': [models.Index(fields=['courier', 'at'], name='couriers_lo_courier_11bb57_idx')],
            },
        ),
    ]
