import hashlib

from django.db import migrations, models
from django.db.models import Count


def normalize_external_ids(apps, schema_editor):
    """Give every historical collection a durable, unique event identity.

    Keep every payment and financial status intact. Reused gateway keys remain
    on the earliest row; later rows and old blank-key rows receive unique audit
    identities. The earliest matching blank-key event receives the same stable
    key generated by the service, so the first retry after upgrade is a replay
    rather than a second collection.
    """
    Payment = apps.get_model('couriers', 'CourierPayment')
    duplicates = (
        Payment.objects.exclude(external_id='')
        .values('external_id')
        .annotate(row_count=Count('id'))
        .filter(row_count__gt=1)
    )
    for group in duplicates.iterator():
        duplicate_ids = list(
            Payment.objects.filter(external_id=group['external_id'])
            .order_by('created_at', 'pk')
            .values_list('pk', flat=True)[1:]
        )
        if duplicate_ids:
            Payment.objects.filter(pk__in=duplicate_ids).update(external_id='')

    used = set(
        Payment.objects.exclude(external_id='')
        .values_list('external_id', flat=True)
    )
    blanks = (
        Payment.objects.filter(external_id='')
        .order_by('created_at', 'pk')
        .values('pk', 'order__uuid', 'courier_id', 'provider', 'amount')
    )
    for row in blanks.iterator():
        identity = '|'.join((
            str(row['order__uuid']), str(row['courier_id'] or ''),
            row['provider'], str(int(row['amount'])),
        ))
        candidate = 'manual:' + hashlib.sha256(
            identity.encode('utf-8')
        ).hexdigest()
        if candidate in used:
            candidate = f"legacy:{row['pk']}"
            suffix = 1
            while candidate in used:
                candidate = f"legacy:{row['pk']}:{suffix}"
                suffix += 1
        Payment.objects.filter(pk=row['pk']).update(external_id=candidate)
        used.add(candidate)


class Migration(migrations.Migration):

    dependencies = [
        ('couriers', '0002_couriernotification_courierpayment_couriersettlement_and_more'),
    ]

    operations = [
        migrations.RunPython(normalize_external_ids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='courierpayment',
            name='external_id',
            field=models.CharField(max_length=128),
        ),
        migrations.AddConstraint(
            model_name='courierpayment',
            constraint=models.UniqueConstraint(
                fields=('external_id',),
                name='uniq_courier_payment_external_id',
            ),
        ),
        migrations.AddConstraint(
            model_name='courierpayment',
            constraint=models.CheckConstraint(
                condition=~models.Q(external_id=''),
                name='courier_payment_external_id_required',
            ),
        ),
    ]
